/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.util;

import com.fasterxml.jackson.databind.node.ObjectNode;

import jakarta.persistence.*;

@Converter
public class NodeConverter implements AttributeConverter<ObjectNode, String> {

  @Override
  public String convertToDatabaseColumn(ObjectNode data) {
    return data != null ? Json.serializer().toString(data) : null;
  }

  @Override
  public ObjectNode convertToEntityAttribute(String data) {
    return data != null ? Json.serializer().nodeFromJson(data) : null;
  }

}
