/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.server.repository;

import com.test.server.model.AbstractPersistentObject;

import org.springframework.data.repository.NoRepositoryBean;

import java.io.Serializable;
import java.util.Optional;

@NoRepositoryBean
public interface AbstractRepository<T extends AbstractPersistentObject, ID extends Serializable>
    extends BaseRepository<T, ID> {

  public Optional<T> findByUid(String uid);

  public T getByUid(String uid);

  public boolean existsByUid(String uid);

  public void deleteByUid(String uid);

}