/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.server.repository;

import com.test.server.domain.Role;

import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface RoleRepository extends AbstractRepository<Role, Long> {

  public Optional<Role> findByProjectIdAndId(Long projectId, Long id);

  public Optional<Role> findByProjectIdAndUid(Long projectId, String uid);

}
