/**
 * NOTE: This class was generated by QSDL.
 */
package app.server;

import app.server.config.AppProperties;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties({AppProperties.class})
public class SpringBootApp {

  public static void main(String[] args) throws Exception {
    SpringApplication.run(SpringBootApp.class, args);
  }

}
