/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.mapper;

import app.server.user.db.RoleEntity;
import app.server.user.dto.Role;
import app.server.user.dto.RoleRequest;
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface RoleMapper {

    RoleRequest toRequest(Role dto);

    @Mapping(target = "id", source = "uid")
    Role toResponse(RoleEntity entity);

    @Mapping(target = "uid", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "project", ignore = true)
    RoleEntity toEntity(RoleRequest dto);

    @InheritConfiguration(name = "toEntity")
    void update(RoleRequest source, @MappingTarget RoleEntity target);
}
