/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.mapper;

import app.server.user.db.UserEntity;
import app.server.user.dto.UserRequest;
import app.server.user.dto.UserResponse;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.Named;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface UserMapStruct {

    @Mapping(target = "tmp", ignore = true)
    UserResponse toDto(UserEntity entity);

    // ignore read only attributes and relations
    @Mapping(target = "uid", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "count", ignore = true)
    @Mapping(target = "tickets", ignore = true)
    UserEntity toEntity(UserRequest dto);

    @Named("replace")
    @InheritConfiguration(name = "toEntity")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.SET_TO_NULL)
    void replace(UserRequest source, @MappingTarget UserEntity target);

    @Named("update")
    @InheritConfiguration(name = "toEntity")
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void update(UserRequest source, @MappingTarget UserEntity target);
}
