/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.service;

import app.server.constant.*;
import app.server.domain.*;
import app.server.domain.entity.*;
import app.server.domain.mapper.*;
import app.server.exception.AppException;
import app.server.exception.AppExceptionUtil;
import app.server.model.Context;
import app.server.model.CursorPage;
import app.server.model.CursorPageable;
import app.server.repository.*;
import app.server.util.PredicateBuilder;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@AllArgsConstructor
public class ProjectService {

    final ProjectRepository projectRepository;

    final ProjectMapper projectMapper;

    ProjectEntity fetchProjectFromDb(Long id) throws AppException {
        return projectRepository.findById(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(Project.class, id));
    }

    public CursorPage<Project> getProjects(CursorPageable pageable, Context context) throws AppException {

        var queryParameters = Arrays.<String>asList("name");
        var predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), ProjectEntity.class);

        var cursorPage = projectRepository.findAll(predicate, pageable);

        var projectEntities = cursorPage.items();
        var projectDtos = projectEntities.stream().map(projectMapper::toResponse).toList();

        return new CursorPage<>(projectDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public Project createProject(ProjectRequest body, Context context) throws AppException {

        var projectEntity = projectMapper.toEntity(body);

        projectEntity = projectRepository.save(projectEntity);

        return projectMapper.toResponse(projectEntity);
    }

    public Project getProject(Long id, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        return projectMapper.toResponse(projectEntity);
    }

    @Transactional
    public Project updateProject(Long id, ProjectRequest body, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        // update dbEntity with all writeable fields - nulls included
        projectMapper.update(body, projectEntity);

        projectEntity = projectRepository.save(projectEntity);

        return projectMapper.toResponse(projectEntity);
    }

    @Transactional
    public Void deleteProject(Long id, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        projectRepository.delete(projectEntity);

        return null;
    }
}
