/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.service;

import app.server.constant.*;
import app.server.domain.*;
import app.server.domain.entity.*;
import app.server.domain.mapper.*;
import app.server.exception.AppException;
import app.server.exception.AppExceptionUtil;
import app.server.model.Context;
import app.server.model.CursorPage;
import app.server.model.CursorPageable;
import app.server.repository.*;
import app.server.util.PredicateBuilder;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@AllArgsConstructor
public class TicketService {

    final TicketRepository ticketRepository;

    final TicketMapper ticketMapper;

    TicketEntity fetchTicketFromDb(Long id) throws AppException {
        return ticketRepository.findById(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(Ticket.class, id));
    }

    @Transactional(readOnly = true)
    public CursorPage<Ticket> getTickets(CursorPageable pageable, Context context) throws AppException {

        var queryParameters = Arrays.<String>asList();
        var predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), TicketEntity.class);

        var cursorPage = ticketRepository.findAll(predicate, pageable);

        var ticketEntities = cursorPage.items();
        var ticketDtos = ticketEntities.stream().map(ticketMapper::toResponse).toList();

        return new CursorPage<>(ticketDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public Ticket createTicket(TicketRequest body, Context context) throws AppException {

        var ticketEntity = ticketMapper.toEntity(body);

        ticketEntity = ticketRepository.save(ticketEntity);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional(readOnly = true)
    public Ticket getTicket(Long id, Context context) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional
    public Ticket updateTicket(Long id, TicketRequest body, Context context) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        // update dbEntity with all writeable fields - nulls included
        ticketMapper.update(body, ticketEntity);

        ticketEntity = ticketRepository.save(ticketEntity);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional
    public Void deleteTicket(Long id, Context context) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        ticketRepository.delete(ticketEntity);

        return null;
    }
}
