/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.management.users;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.test.model.*;


@Validated
@RequestMapping("${server.base-path:/}")
@Controller
public class UsersController {

  private final NativeWebRequest request;

  @Autowired
  UsersService usersService;

  @Autowired
  public UsersController(NativeWebRequest request) {
    this.request = request;
  }

  public Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /roles/{role_role}/users : List Users
   *
   * @param roleRole (required)
   * @param name
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/roles/{role_role}/users",
    produces = { "application/json" }
  )
  public ResponseEntity<UserList> getUsersForRole(@PathVariable("role_role") Long roleRole, @Valid @RequestParam(value = "name", required = false) Long name, ApiPageable pageable) throws Exception {
    UserList response = usersService.getUsersForRole(roleRole, name, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /roles/{role_role}/users/add : Add User
   *
   * @param roleRole (required)
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/roles/{role_role}/users/add",
    consumes = { "application/json" }
  )
  public ResponseEntity<Void> addUserForRole(@PathVariable("role_role") Long roleRole, @Valid @RequestBody Long name) throws Exception {
    usersService.addUserForRole(roleRole, name);
    return new ResponseEntity<>(HttpStatus.OK);
  }

  /**
   * POST /roles/{role_role}/users/remove : Remove User
   *
   * @param roleRole (required)
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/roles/{role_role}/users/remove",
    consumes = { "application/json" }
  )
  public ResponseEntity<Void> removeUserForRole(@PathVariable("role_role") Long roleRole, @Valid @RequestBody Long name) throws Exception {
    usersService.removeUserForRole(roleRole, name);
    return new ResponseEntity<>(HttpStatus.OK);
  }

  /**
   * GET /users : List Users
   *
   * @param name
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/users",
    produces = { "application/json" }
  )
  public ResponseEntity<UserList> getUsers(@Valid @RequestParam(value = "name", required = false) Long name, ApiPageable pageable) throws Exception {
    UserList response = usersService.getUsers(name, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /users : Create a User
   *
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/users",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<User> createUser(@Valid @RequestBody User body) throws Exception {
    User response = usersService.createUser(body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /users/{name} : Read the specified User
   *
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/users/{name}",
    produces = { "application/json" }
  )
  public ResponseEntity<User> getUser(@PathVariable("name") Long name) throws Exception {
    User response = usersService.getUser(name);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /users/{name} : Replace the specified User
   *
   * @param name (required)
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PutMapping(
    value = "/users/{name}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<User> replaceUser(@PathVariable("name") Long name, @Valid @RequestBody User body) throws Exception {
    User response = usersService.replaceUser(name, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /users/{name} : Update the specified User
   *
   * @param name (required)
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PatchMapping(
    value = "/users/{name}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<User> updateUser(@PathVariable("name") Long name, @Valid @RequestBody User body) throws Exception {
    User response = usersService.updateUser(name, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /users/{name} : Delete the specified User
   *
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @DeleteMapping(
    value = "/users/{name}"
  )
  public ResponseEntity<Void> deleteUser(@PathVariable("name") Long name) throws Exception {
    usersService.deleteUser(name);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
