/**
 * NOTE: This record was generated by QSDL.
 */
package app.server.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.soabase.recordbuilder.core.RecordBuilder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import tools.jackson.databind.node.ObjectNode;

@RecordBuilder
public record Project(
// @formatter:off

    @Min(0)
    @Max(Long.MAX_VALUE)
    @JsonProperty(value = "id")
    Long id,

    @Size(min = 0, max = 255)
    @JsonProperty(value = "name")
    String name,

    @Size(min = 0, max = 255)
    @JsonProperty(value = "description")
    String description,

    @Size(min = 0, max = 255)
    @JsonProperty(value = "creation_by")
    String creationBy,

    @JsonProperty(value = "creation_date")
    LocalDate creationDate,

    @Size(min = 0, max = 255)
    @JsonProperty(value = "last_update_by")
    String lastUpdateBy,

    @JsonProperty(value = "last_update_date")
    OffsetDateTime lastUpdateDate,

    @JsonProperty(value = "meta_inf")
    ObjectNode metaInf
) {
}