/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain;

import app.server.constant.Status;
import app.server.model.AbstractClass;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import lombok.extern.jackson.Jacksonized;

@Getter
@Setter
@Builder
@Jacksonized
@EqualsAndHashCode(callSuper = false)
public class Ticket extends AbstractClass {

  @Min(0)
  @Max(Long.MAX_VALUE)
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @Min(0)
  @Max(Integer.MAX_VALUE)
  @Builder.Default
  @JsonProperty(value = "number")
  private Integer number = 42;

  @Size(min = 0, max = 255)
  @Builder.Default
  @JsonProperty(value = "title")
  private String title = "Witty Title";

  @Size(min = 0, max = 255)
  @JsonProperty(value = "body")
  private String body;

  @Builder.Default
  @JsonProperty(value = "status")
  private Status status = Status.OPEN;
}
