/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.api;

import app.server.common.api.BaseController;
import app.server.common.constants.*;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.JsonMergePatchUtil;
import app.server.common.util.Validator;
import app.server.user.api.RoleApi;
import app.server.user.dto.*;
import app.server.user.mapper.RoleMapper;
import app.server.user.service.RoleService;
import jakarta.json.JsonMergePatch;
import java.util.List;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import tools.jackson.databind.node.ObjectNode;

@Controller
@AllArgsConstructor
public class RoleController extends BaseController implements RoleApi {

    final RoleService roleService;
    final RoleMapper roleMapper;

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<CursorPage<RoleResponse>> getRoles(String projectId, CursorPageable pageable) {
        CursorPage<RoleResponse> response = roleService.getRoles(projectId, pageable, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<RoleResponse> createRole(String projectId, RoleRequest body) {
        Validator.validate(body);
        RoleResponse response = roleService.createRole(projectId, body, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<RoleResponse> getRole(String projectId, String id) {
        RoleResponse response = roleService.getRole(projectId, id, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<RoleResponse> updateRole(String projectId, String id, JsonMergePatch patch) {
        RoleResponse current = roleService.getRole(projectId, id, super.getContext());
        RoleRequest target = roleMapper.toRequest(current);
        RoleRequest request = JsonMergePatchUtil.apply(patch, target);

        Validator.validate(request);
        RoleResponse response = roleService.updateRole(projectId, id, request, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> deleteRole(String projectId, String id) {
        roleService.deleteRole(projectId, id, super.getContext());
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
