image: ghcr.io/astral-sh/uv:python3.13-alpine

cache:
  paths:
    - .venv/

before_script:
  - sh dev.sh init

stages:
  - test
  - deploy

test:
  script:
    - sh dev.sh tests
  only:
    - master
  artifacts:
    paths:
      - dist/
    reports:
      junit: dist/tests/report.xml

deploy:
  stage: deploy
  script:
    - sh dev.sh build
    - uv publish --publish-url $POETRY_REGISTRY --username $POETRY_USER --password $POETRY_TOKEN
  only:
    - tags
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv dist/coverage/ public/
  only:
    - master
  artifacts:
    paths:
    - public/
