/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import com.test.api.RoleApi;
import com.test.domain.*;
import com.test.model.*;
import com.test.service.RoleService;
import com.test.util.Validator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;

@Validated
@Controller
public class RoleController extends BaseController implements RoleApi {

  @Autowired
  RoleService roleService;

  @Autowired
  public RoleController(NativeWebRequest request) {
    super(request);
  }

  /**
   * GET /projects/{project_id}/roles : List Roles
   */
  public ResponseEntity<CursorPage> getRoles(@PathVariable("project_id") Long projectId, CursorPageable pageable) throws Exception {
    CursorPage response = roleService.getRoles(projectId, super.getQueryMap(), pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /projects/{project_id}/roles : Create a Role
   */
  public ResponseEntity<Role> createRole(@PathVariable("project_id") Long projectId, @Valid @RequestBody Role body) throws Exception {
    Role response = roleService.createRole(projectId, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /projects/{project_id}/roles/{id} : Read the specified Role
   */
  public ResponseEntity<Role> getRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id) throws Exception {
    Role response = roleService.getRole(projectId, id);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /projects/{project_id}/roles/{id} : Replace the specified Role
   */
  public ResponseEntity<Role> replaceRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id, @Valid @RequestBody Role body) throws Exception {
    Role response = roleService.replaceRole(projectId, id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /projects/{project_id}/roles/{id} : Update the specified Role
   */
  public ResponseEntity<Role> updateRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id, @RequestBody Role body) throws Exception {
    Validator.validateExRequired(body);
    Role response = roleService.updateRole(projectId, id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /projects/{project_id}/roles/{id} : Delete the specified Role
   */
  public ResponseEntity<Void> deleteRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id) throws Exception {
    roleService.deleteRole(projectId, id);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
