/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.*;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.test.domain.*;
import com.test.model.*;
import com.test.service.*;
import com.test.util.Validator;


@Validated
@RequestMapping("${server.base-path:/api/v1}")
@Controller
public class RoleController {

  private final NativeWebRequest request;

  @Autowired
  RoleService roleService;

  @Autowired
  public RoleController(NativeWebRequest request) {
    this.request = request;
  }

  public Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /projects/{project_id}/roles : List Roles
   */
  @GetMapping(
    value = "/projects/{project_id}/roles",
    produces = { "application/json" }
  )
  public ResponseEntity<ObjectList> getRoles(@PathVariable("project_id") Long projectId, AppPageable pageable) throws Exception {
    ObjectList response = roleService.getRoles(projectId, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /projects/{project_id}/roles : Create a Role
   */
  @PostMapping(
    value = "/projects/{project_id}/roles",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Role> createRole(@PathVariable("project_id") Long projectId, @Valid @RequestBody Role body) throws Exception {
    Role response = roleService.createRole(projectId, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /projects/{project_id}/roles/{id} : Read the specified Role
   */
  @GetMapping(
    value = "/projects/{project_id}/roles/{id}",
    produces = { "application/json" }
  )
  public ResponseEntity<Role> getRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id) throws Exception {
    Role response = roleService.getRole(projectId, id);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /projects/{project_id}/roles/{id} : Replace the specified Role
   */
  @PutMapping(
    value = "/projects/{project_id}/roles/{id}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Role> replaceRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id, @Valid @RequestBody Role body) throws Exception {
    Role response = roleService.replaceRole(projectId, id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /projects/{project_id}/roles/{id} : Update the specified Role
   */
  @PatchMapping(
    value = "/projects/{project_id}/roles/{id}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Role> updateRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id, @RequestBody Role body) throws Exception {
    Validator.validateExRequired(body);
    Role response = roleService.updateRole(projectId, id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /projects/{project_id}/roles/{id} : Delete the specified Role
   */
  @DeleteMapping(
    value = "/projects/{project_id}/roles/{id}"
  )
  public ResponseEntity<Void> deleteRole(@PathVariable("project_id") Long projectId, @PathVariable("id") Long id) throws Exception {
    roleService.deleteRole(projectId, id);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
