/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.*;
import javax.validation.Valid;

import com.test.domain.*;
import com.test.model.*;
import com.test.service.*;
import com.test.util.Validator;


@Validated
@RequestMapping("${server.base-path:/api/v1}")
@Controller
public class TicketController extends BaseController {

  @Autowired
  TicketService ticketService;

  @Autowired
  public TicketController(NativeWebRequest request) {
    super(request);
  }

  /**
   * GET /tickets : List Tickets
   */
  @GetMapping(
    value = "/tickets",
    produces = { "application/json" }
  )
  public ResponseEntity<ObjectList> getTickets(AppPageable pageable) throws Exception {
    ObjectList response = ticketService.getTickets(super.getQueryMap(), pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /tickets : Create a Ticket
   */
  @PostMapping(
    value = "/tickets",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> createTicket(@Valid @RequestBody Ticket body) throws Exception {
    Ticket response = ticketService.createTicket(body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /tickets/{id} : Read the specified Ticket
   */
  @GetMapping(
    value = "/tickets/{id}",
    produces = { "application/json" }
  )
  public ResponseEntity<Ticket> getTicket(@PathVariable("id") Long id) throws Exception {
    Ticket response = ticketService.getTicket(id);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /tickets/{id} : Replace the specified Ticket
   */
  @PutMapping(
    value = "/tickets/{id}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> replaceTicket(@PathVariable("id") Long id, @Valid @RequestBody Ticket body) throws Exception {
    Ticket response = ticketService.replaceTicket(id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /tickets/{id} : Update the specified Ticket
   */
  @PatchMapping(
    value = "/tickets/{id}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> updateTicket(@PathVariable("id") Long id, @RequestBody Ticket body) throws Exception {
    Validator.validateExRequired(body);
    Ticket response = ticketService.updateTicket(id, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /tickets/{id} : Delete the specified Ticket
   */
  @DeleteMapping(
    value = "/tickets/{id}"
  )
  public ResponseEntity<Void> deleteTicket(@PathVariable("id") Long id) throws Exception {
    ticketService.deleteTicket(id);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
