/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.service;

import app.server.common.constants.*;
import app.server.common.db.*;
import app.server.common.exception.AppException;
import app.server.common.exception.AppExceptionUtil;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.PredicateBuilder;
import app.server.project.db.*;
import app.server.project.dto.*;
import app.server.project.mapper.*;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@AllArgsConstructor
public class ProjectService {

    final ProjectRepository projectRepository;

    final ProjectMapper projectMapper;

    ProjectEntity fetchProjectFromDb(String id) throws AppException {
        return projectRepository.findByUid(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(ProjectResponse.class, id));
    }

    public CursorPage<ProjectResponse> getProjects(CursorPageable pageable, Context context) throws AppException {

        var queryParameters = Arrays.<String>asList("name");
        var predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), ProjectEntity.class);

        var cursorPage = projectRepository.findAll(predicate, pageable);

        var projectEntities = cursorPage.items();
        var projectDtos = projectEntities.stream().map(projectMapper::toResponse).toList();

        return new CursorPage<>(projectDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public ProjectResponse createProject(ProjectRequest body, Context context) throws AppException {

        var projectEntity = projectMapper.toEntity(body);

        projectEntity = projectRepository.save(projectEntity);

        return projectMapper.toResponse(projectEntity);
    }

    public ProjectResponse getProject(String id, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        return projectMapper.toResponse(projectEntity);
    }

    @Transactional
    public ProjectResponse updateProject(String id, ProjectRequest body, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        // update dbEntity with all writeable fields - nulls included
        projectMapper.update(body, projectEntity);

        projectEntity = projectRepository.save(projectEntity);

        return projectMapper.toResponse(projectEntity);
    }

    @Transactional
    public Void deleteProject(String id, Context context) throws AppException {

        var projectEntity = fetchProjectFromDb(id);

        projectRepository.delete(projectEntity);

        return null;
    }
}
