/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.mapper;

import app.server.project.db.ProjectEntity;
import app.server.project.dto.ProjectRequest;
import app.server.project.dto.ProjectResponse;
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface ProjectMapper {

    @Mapping(target = "archive", ignore = true)
    ProjectRequest toRequest(ProjectResponse dto);

    @Mapping(target = "id", source = "uid")
    ProjectResponse toResponse(ProjectEntity entity);

    @Mapping(target = "uid", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "creationBy", ignore = true)
    @Mapping(target = "creationDate", ignore = true)
    @Mapping(target = "lastUpdateBy", ignore = true)
    @Mapping(target = "lastUpdateDate", ignore = true)
    @Mapping(target = "roles", ignore = true)
    ProjectEntity toEntity(ProjectRequest dto);

    @InheritConfiguration(name = "toEntity")
    void update(ProjectRequest source, @MappingTarget ProjectEntity target);
}
