/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.exception;

import java.util.List;

import com.test.config.Errors;
import com.test.model.ApiError;

public class ApiException extends Exception {

  static final long serialVersionUID = 1L;

  private ApiError apiError;

  public ApiException(Errors error) {
    super(error.getMessage());
    this.apiError = error.getApiError();
  }

  public ApiException(Errors error, String details) {
    super(error.getMessage());
    this.apiError = error.getApiError();
    this.apiError.addDetailsItem(details);
  }

  public ApiException(Errors error, List<String> details) {
    super(error.getMessage());
    this.apiError = error.getApiError();
    this.apiError.setDetails(details);
  }

  public ApiError getApiError() {
    return apiError;
  }

}
