/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.exception;

import com.test.config.Errors;
import com.test.model.AppError;

import java.util.List;

public class AppException extends Exception {

  static final long serialVersionUID = 1L;

  private final AppError AppError;

  public AppException(Errors error) {
    super(error.message());
    this.AppError = error.toAppError();
  }

  public AppException(Errors error, String detail) {
    super(error.message());
    this.AppError = error.toAppError(detail);
  }

  public AppException(Errors error, List<String> details) {
    super(error.message());
    this.AppError = error.toAppError(details);
  }

  public AppError getAppError() {
    return AppError;
  }


  public static AppException entityNotFound(Class<?> cls, Long id) {
    return new AppException(Errors.ENTITY_NOT_FOUND,
        "No %s entity with id %s exists!"
            .formatted(cls.getSimpleName(), id));
  }

}
