/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.exception;

import com.test.config.ErrorCodes;
import com.test.model.AppError;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.*;
import org.springframework.validation.*;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.*;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

import javax.servlet.http.HttpServletRequest;

import java.util.*;

@Slf4j
@ControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

  /**
   * Required for nested object validation
   */
  @InitBinder
  private void initDirectFieldAccess(DataBinder dataBinder) {
    dataBinder.initDirectFieldAccess();
  }

  private ResponseEntity<Object> buildResponseEntity(AppError AppError,
      HttpServletRequest httpRequest) {

    AppError.path = httpRequest.getRequestURI();

    log.warn(AppError.toString());

    return new ResponseEntity<>(AppError, HttpStatus.valueOf(AppError.status));
  }

  /**
   * Handle our Exceptions.
   */
  @ExceptionHandler({AppException.class})
  protected ResponseEntity<Object> handleAppException(AppException ex, WebRequest request,
      HttpServletRequest httpRequest) {

    return buildResponseEntity(ex.getAppError(), httpRequest);
  }

  /**
   * Fall-back handler.
   * 
   * Catch-all other exceptions that don't have specific handlers.
   */
  @ExceptionHandler({Exception.class})
  public ResponseEntity<Object> handleAll(Exception ex, WebRequest request,
      HttpServletRequest httpRequest) {

    log.error("Caught unhandeled exception:", ex);

    AppError AppError = ErrorCodes.INTERNAL_SERVER_ERROR.toAppError(ex.toString());

    return buildResponseEntity(AppError, httpRequest);
  }

  /**
   * Handles standard Spring MVC Exceptions.
   */
  @Override
  protected ResponseEntity<Object> handleExceptionInternal(Exception ex, Object body,
      HttpHeaders headers, HttpStatus status, WebRequest request) {

    HttpServletRequest httpRequest = ((ServletWebRequest) request).getRequest();

    AppError AppError = ErrorCodes.BAD_REQEST.toAppError(ex.toString());

    return buildResponseEntity(AppError, httpRequest);
  }

  /**
   * Handles bean validation related Exceptions.
   */
  @Override
  protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,
      HttpHeaders headers, HttpStatus status, WebRequest request) {

    HttpServletRequest httpRequest = ((ServletWebRequest) request).getRequest();

    List<String> errors = new ArrayList<String>();
    for (FieldError error : ex.getBindingResult().getFieldErrors()) {
      errors.add(error.getField() + ": " + error.getDefaultMessage());
    }

    for (ObjectError error : ex.getBindingResult().getGlobalErrors()) {
      errors.add(error.getObjectName() + ": " + error.getDefaultMessage());
    }

    AppError AppError = ErrorCodes.BAD_REQEST.toAppError(errors);

    return buildResponseEntity(AppError, httpRequest);
  }

}
