/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.management.user;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.persistence.EntityNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.test.constants.AppError;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.model.*;

@Service
public class UserService {

  private static Logger log = LoggerFactory.getLogger(UserService.class.getSimpleName());


  @PostConstruct
  private void init() {

  }

  public UserList getUsersForRole(Long roleRole, Long name, ApiPageable pageable) throws Exception {

  return null;
  }

  public Void addUserToRole(Long roleRole, Long name) throws Exception {

  return null;
  }

  public Void removeUserFromRole(Long roleRole, Long name) throws Exception {

  return null;
  }

  public UserList getUsers(Long name, ApiPageable pageable) throws Exception {

  return null;
  }

  public User createUser(User body) throws Exception {

  return null;
  }

  public User getUser(Long name) throws Exception {

  return null;
  }

  public User replaceUser(Long name, User body) throws Exception {

  return null;
  }

  public User updateUser(Long name, User body) throws Exception {

  return null;
  }

  public Void deleteUser(Long name) throws Exception {

  return null;
  }

}
