from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EDeeplyNestedBaseTypes(BaseE2ETest):
    """Test E2E for DEEPLY_NESTED_BASE_TYPES testcase"""

    TESTCASE = """\
      base GeoCoordinates {
        latitude: Float
        longitude: Float
      }
      base ContactInfo {
        email: String
        phone: String
        location: GeoCoordinates
      }
      base Address {
        street: String
        city: String
        contact: ContactInfo
      }
      type Company {
        name: String
        headquarters: Address
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          CREATE TABLE IF NOT EXISTS t_company (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            uid VARCHAR UNIQUE,
            iv INTEGER,
            creation_date TIMESTAMP NOT NULL,
            modification_date TIMESTAMP,
            name TEXT,
            headquarters_street TEXT,
            headquarters_city TEXT,
            headquarters_contact_email TEXT,
            headquarters_contact_phone TEXT,
            headquarters_contact_location_latitude REAL,
            headquarters_contact_location_longitude REAL
          );
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        schemas = openapi_schema["components"]["schemas"]

        assert schemas["ContactInfo"]["properties"]["location"] == {"$ref": "#/components/schemas/GeoCoordinates"}
        assert schemas["Address"]["properties"]["contact"] == {"$ref": "#/components/schemas/ContactInfo"}
        company = schemas["Company"]["properties"]
        assert company["headquarters"] == {"$ref": "#/components/schemas/Address"}
        assert schemas["GeoCoordinates"]["properties"]["latitude"] == {
            "type": "number",
            "format": "float",
            "minimum": 0,
        }

    def test_spring(self, srcgen: Path) -> None:
        src_root = srcgen / "src" / "main" / "java"

        company_entity = next(src_root.rglob("CompanyEntity.java")).read_text(encoding="utf-8")
        expected_fields = {
            "headquartersStreet": "String",
            "headquartersCity": "String",
            "headquartersContactEmail": "String",
            "headquartersContactPhone": "String",
            "headquartersContactLocationLatitude": "Float",
            "headquartersContactLocationLongitude": "Float",
        }
        for field, type_name in expected_fields.items():
            assert f"private {type_name} {field};" in company_entity

        company_request = next(src_root.rglob("CompanyRequest.java")).read_text(encoding="utf-8")
        assert "Address headquarters" in company_request
        assert '@JsonProperty(value = "headquarters")' in company_request

        company_mapper = next(src_root.rglob("CompanyMapper.java")).read_text(encoding="utf-8")
        assert (
            '@Mapping(target = "headquartersContactLocationLongitude", '
            'source = "headquarters.contact.location.longitude")' in company_mapper
        )
        assert "CompanyEntity toEntity(CompanyRequest dto);" in company_mapper

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn(srcgen)
