/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.exception.AppException;
import app.server.common.model.AppError;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Json;
import app.server.project.db.ProjectEntity;
import app.server.project.db.ProjectRepository;
import app.server.user.db.RoleEntity;
import app.server.user.db.RoleRepository;
import app.server.user.dto.Role;
import app.server.user.mapper.RoleMapStruct;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class RoleServiceTest {

    @Mock
    RoleRepository repository;

    @Mock
    RoleMapStruct mockedMapper;

    @Mock
    ProjectRepository projectRepository;

    RoleService service;

    @Autowired
    RoleMapStruct mapper;

    static Long one = 1L;

    @BeforeEach
    void setUp() {
        service = new RoleService(projectRepository, repository, mockedMapper);
    }

    @Test
    void whenGetRoles_thenOk() throws Exception {

        // Given
        List<RoleEntity> roleEntityList = TestUtils.getRandomEntity(RoleEntity.class, 5);
        List<Role> roleList = roleEntityList.stream().map(mapper::toDto).toList();
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<RoleEntity>(roleEntityList, null, 6L));

        when(mockedMapper.toDto(any(RoleEntity.class)))
                .thenReturn(roleList.get(0))
                .thenReturn(roleList.get(1))
                .thenReturn(roleList.get(2))
                .thenReturn(roleList.get(3))
                .thenReturn(roleList.get(4));

        // When
        CursorPage<Role> response = service.getRoles(one, new CursorPageable(null, 5, true), new Context());

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.serializer().toString(roleList),
                new JSONArray(Json.serializer().toString(response.items())),
                false);
    }

    @Test
    void whenCreateRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(mockedMapper.toEntity(any(Role.class)))
                .thenReturn(roleEntity);

        when(repository.save(eq(roleEntity)))
                .thenReturn(roleEntity);

        when(mockedMapper.toDto(any(RoleEntity.class)))
                .thenReturn(role);

        // When
        Role response = service.createRole(one, role, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.serializer().toString(role),
                new JSONObject(Json.serializer().toString(response)),
                false);
    }

    @Test
    void whenGetRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        when(mockedMapper.toDto(any(RoleEntity.class)))
                .thenReturn(role);

        // When
        Role response = service.getRole(one, roleEntity.getId(), new Context());

        // Then
        JSONAssert.assertEquals(
                Json.serializer().toString(role),
                new JSONObject(Json.serializer().toString(response)),
                false);
    }

    @Test
    public void whenGetRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.getRole(one, roleEntity.getId(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenReplaceRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        when(repository.save(eq(roleEntity)))
                .thenReturn(roleEntity);

        when(mockedMapper.toDto(any(RoleEntity.class)))
                .thenReturn(role);

        // When
        Role response = service.replaceRole(one, roleEntity.getId(), role, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.serializer().toString(role),
                new JSONObject(Json.serializer().toString(response)),
                false);
    }

    @Test
    public void whenReplaceRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.replaceRole(one, roleEntity.getId(), role, new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenUpdateRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        when(repository.save(eq(roleEntity)))
                .thenReturn(roleEntity);

        when(mockedMapper.toDto(any(RoleEntity.class)))
                .thenReturn(role);

        // When
        Role response = service.updateRole(one, roleEntity.getId(), role, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.serializer().toString(role),
                new JSONObject(Json.serializer().toString(response)),
                false);
    }

    @Test
    public void whenUpdateRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        Role role = mapper.toDto(roleEntity);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.updateRole(one, roleEntity.getId(), role, new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenDeleteRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        // When & Then
        service.deleteRole(one, roleEntity.getId(), new Context());
    }

    @Test
    public void whenDeleteRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandomEntity(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandomEntity(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.deleteRole(one, roleEntity.getId(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }
}
