/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.db.TicketEntity;
import app.server.common.db.TicketRepository;
import app.server.common.exception.AppException;
import app.server.common.model.AppError;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Json;
import app.server.user.db.UserEntity;
import app.server.user.db.UserRepository;
import app.server.user.dto.UserRequest;
import app.server.user.dto.UserResponse;
import app.server.user.mapper.UserMapStruct;
import app.server.user.mapper.UserMapStructImpl;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class UserServiceTest {

    @MockitoBean
    UserRepository repository;

    @MockitoBean
    UserMapStruct mockedMapper;

    @MockitoBean
    TicketRepository ticketRepository;

    UserService service;

    UserMapStruct mapper;

    static Long one = 1L;

    @BeforeEach
    void setUp() {
        mapper = new UserMapStructImpl();
        service = new UserService(ticketRepository, repository, mockedMapper);
    }

    @Test
    void whenGetUsersForTicket_thenOk() throws Exception {

        // Given
        List<UserEntity> userEntityList = TestUtils.getRandom(UserEntity.class, 5);
        List<UserResponse> userList = userEntityList.stream().map(mapper::toDto).toList();
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userList.get(0))
                .thenReturn(userList.get(1))
                .thenReturn(userList.get(2))
                .thenReturn(userList.get(3))
                .thenReturn(userList.get(4));

        // When
        CursorPage<UserResponse> response = service.getUsersForTicket(one, new CursorPageable(null, 5, true), new Context());

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(userList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenAddUserToTicket_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findById(eq(testParent.getId())))
                .thenReturn(Optional.of(testParent));

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(null);

        // When
        service.addUserToTicket(testParent.getId(), userEntity.getId(), new Context());

        // Then

    }

    @Test
    void whenRemoveUserFromTicket_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findById(eq(testParent.getId())))
                .thenReturn(Optional.of(testParent));

        when(repository.findByTicketsIdAndId(eq(testParent.getId()), eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(null);

        // When
        service.removeUserFromTicket(testParent.getId(), userEntity.getId(), new Context());

        // Then

    }

    @Test
    void whenGetUsers_thenOk() throws Exception {

        // Given
        List<UserEntity> userEntityList = TestUtils.getRandom(UserEntity.class, 5);
        List<UserResponse> userList = userEntityList.stream().map(mapper::toDto).toList();

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userList.get(0))
                .thenReturn(userList.get(1))
                .thenReturn(userList.get(2))
                .thenReturn(userList.get(3))
                .thenReturn(userList.get(4));

        // When
        CursorPage<UserResponse> response = service.getUsers(new CursorPageable(null, 5, true), new Context());

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(userList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenCreateUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);
        UserResponse userResponse = mapper.toDto(userEntity);

        when(mockedMapper.toEntity(any(UserRequest.class)))
                .thenReturn(userEntity);

        when(repository.save(eq(userEntity)))
                .thenReturn(userEntity);

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userResponse);

        // When
        UserResponse response = service.createUser(userRequest, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    void whenGetUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserResponse userResponse = mapper.toDto(userEntity);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userResponse);

        // When
        UserResponse response = service.getUser(userEntity.getId(), new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenGetUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.getUser(userEntity.getId(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenReplaceUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);
        UserResponse userResponse = mapper.toDto(userEntity);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(userEntity);

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userResponse);

        // When
        UserResponse response = service.replaceUser(userEntity.getId(), userRequest, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenReplaceUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.replaceUser(userEntity.getId(), userRequest, new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenUpdateUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);
        UserResponse userResponse = mapper.toDto(userEntity);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(userEntity);

        when(mockedMapper.toDto(any(UserEntity.class)))
                .thenReturn(userResponse);

        // When
        UserResponse response = service.updateUser(userEntity.getId(), userRequest, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenUpdateUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.updateUser(userEntity.getId(), userRequest, new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenDeleteUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.of(userEntity));

        // When & Then
        service.deleteUser(userEntity.getId(), new Context());
    }

    @Test
    public void whenDeleteUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findById(eq(userEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.deleteUser(userEntity.getId(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }
}
