/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.db.TicketEntity;
import app.server.common.db.TicketRepository;
import app.server.common.exception.AppException;
import app.server.common.model.AppError;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Json;
import app.server.user.db.UserEntity;
import app.server.user.db.UserRepository;
import app.server.user.dto.User;
import app.server.user.dto.UserRequest;
import app.server.user.mapper.UserMapper;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class UserServiceTest {

    @MockitoBean
    UserRepository repository;

    @MockitoBean
    TicketRepository ticketRepository;

    UserService service;

    @Autowired
    UserMapper mapper;

    static String one = "1";

    @BeforeEach
    void setUp() {
        service = new UserService(ticketRepository, repository, mapper);
    }

    @Test
    void whenGetUsersForTicket_thenOk() throws Exception {

        // Given
        List<UserEntity> userEntityList = TestUtils.getRandom(UserEntity.class, 5);
        List<User> userList = userEntityList.stream().map(mapper::toResponse).toList();
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findByUid(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

        // When
        CursorPage<User> response = service.getUsersForTicket(one, new CursorPageable(null, 5, true));

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(userList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenAddUserToTicket_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findByUid(eq(testParent.getUid())))
                .thenReturn(Optional.of(testParent));

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(null);

        // When
        service.addUserToTicket(testParent.getUid(), userEntity.getUid());

        // Then

    }

    @Test
    void whenRemoveUserFromTicket_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        TicketEntity testParent = TestUtils.getRandom(TicketEntity.class);

        when(ticketRepository.findByUid(eq(testParent.getUid())))
                .thenReturn(Optional.of(testParent));

        when(repository.findByTicketsIdAndUid(eq(testParent.getId()), eq(userEntity.getUid())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(null);

        // When
        service.removeUserFromTicket(testParent.getUid(), userEntity.getUid());

        // Then

    }

    @Test
    void whenGetUsers_thenOk() throws Exception {

        // Given
        List<UserEntity> userEntityList = TestUtils.getRandom(UserEntity.class, 5);
        List<User> userList = userEntityList.stream().map(mapper::toResponse).toList();

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

        // When
        CursorPage<User> response = service.getUsers(new CursorPageable(null, 5, true));

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(userList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenCreateUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);
        User userResponse = mapper.toResponse(userEntity);

        when(repository.save(any(UserEntity.class)))
                .thenReturn(userEntity);

        // When
        User response = service.createUser(userRequest);

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    void whenGetUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        User userResponse = mapper.toResponse(userEntity);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.of(userEntity));

        // When
        User response = service.getUser(userEntity.getUid());

        // Then
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenGetUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.getUser(userEntity.getUid());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenUpdateUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.of(userEntity));

        when(repository.save(eq(userEntity)))
                .thenReturn(userEntity);

        // When
        User response = service.updateUser(userEntity.getUid(), userRequest);

        // Then
        User userResponse = mapper.toResponse(userEntity);
        JSONAssert.assertEquals(
                Json.toString(userResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenUpdateUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);
        UserRequest userRequest = TestUtils.getRandom(UserRequest.class);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.updateUser(userEntity.getUid(), userRequest);
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenDeleteUser_thenOk() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.of(userEntity));

        // When & Then
        service.deleteUser(userEntity.getUid());
    }

    @Test
    public void whenDeleteUserWithInvalidId_thenError() throws Exception {

        // Given
        UserEntity userEntity = TestUtils.getRandom(UserEntity.class);

        when(repository.findByUid(eq(userEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.deleteUser(userEntity.getUid());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }
}
