/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.db.TicketEntity;
import app.server.common.db.TicketRepository;
import app.server.common.exception.AppException;
import app.server.common.model.AppError;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Json;
import app.server.user.db.UserEntity;
import app.server.user.db.UserRepository;
import app.server.user.dto.User;
import app.server.user.mapper.UserMapStruct;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class UserServiceTest {

  @Mock
  UserRepository repository;

  @Mock
  UserMapStruct mockedMapper;

  @Mock
  TicketRepository ticketRepository;

  UserService service;

  @Autowired
  UserMapStruct mapper;

  static Long one = 1L;

  @BeforeEach
  void setUp() {
    service = new UserService(ticketRepository, repository, mockedMapper);
  }

  @Test
  void whenGetUsersForTicket_thenOk() throws Exception {

    // Given
    List<UserEntity> userEntityList = TestUtils.getRandomEntity(UserEntity.class, 5);
    List<User> userList = userEntityList.stream().map(mapper::toDto).toList();
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(one)))
        .thenReturn(Optional.of(testParent));

    when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
        .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(userList.get(0))
        .thenReturn(userList.get(1))
        .thenReturn(userList.get(2))
        .thenReturn(userList.get(3))
        .thenReturn(userList.get(4));

    // When
    CursorPage<User> response = service.getUsersForTicket(one, new CursorPageable(null, 5, true), new Context());

    // Then
    assertEquals(5L, response.count());
    assertEquals(6L, response.totalCount());

    JSONAssert.assertEquals(
        Json.serializer().toString(userList),
        new JSONArray(Json.serializer().toString(response.items())),
        false);
  }

  @Test
  void whenAddUserToTicket_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(testParent.getId())))
        .thenReturn(Optional.of(testParent));

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(null);

    // When
    service.addUserToTicket(testParent.getId(), userEntity.getId(), new Context());

    // Then

  }

  @Test
  void whenRemoveUserFromTicket_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(testParent.getId())))
        .thenReturn(Optional.of(testParent));

    when(repository.findByTicketsIdAndId(eq(testParent.getId()), eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(null);

    // When
    service.removeUserFromTicket(testParent.getId(), userEntity.getId(), new Context());

    // Then

  }

  @Test
  void whenGetUsers_thenOk() throws Exception {

    // Given
    List<UserEntity> userEntityList = TestUtils.getRandomEntity(UserEntity.class, 5);
    List<User> userList = userEntityList.stream().map(mapper::toDto).toList();

    when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
        .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6L));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(userList.get(0))
        .thenReturn(userList.get(1))
        .thenReturn(userList.get(2))
        .thenReturn(userList.get(3))
        .thenReturn(userList.get(4));

    // When
    CursorPage<User> response = service.getUsers(new CursorPageable(null, 5, true), new Context());

    // Then
    assertEquals(5L, response.count());
    assertEquals(6L, response.totalCount());

    JSONAssert.assertEquals(
        Json.serializer().toString(userList),
        new JSONArray(Json.serializer().toString(response.items())),
        false);
  }

  @Test
  void whenCreateUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(mockedMapper.toEntity(any(User.class)))
        .thenReturn(userEntity);

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.createUser(user, new Context());

    // Then
    JSONAssert.assertEquals(
        Json.serializer().toString(user),
        new JSONObject(Json.serializer().toString(response)),
        false);
  }

  @Test
  void whenGetUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.getUser(userEntity.getId(), new Context());

    // Then
    JSONAssert.assertEquals(
        Json.serializer().toString(user),
        new JSONObject(Json.serializer().toString(response)),
        false);
  }

  @Test
  public void whenGetUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.getUser(userEntity.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenReplaceUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.replaceUser(userEntity.getId(), user, new Context());

    // Then
    JSONAssert.assertEquals(
        Json.serializer().toString(user),
        new JSONObject(Json.serializer().toString(response)),
        false);
  }

  @Test
  public void whenReplaceUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.replaceUser(userEntity.getId(), user, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenUpdateUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.updateUser(userEntity.getId(), user, new Context());

    // Then
    JSONAssert.assertEquals(
        Json.serializer().toString(user),
        new JSONObject(Json.serializer().toString(response)),
        false);
  }

  @Test
  public void whenUpdateUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.updateUser(userEntity.getId(), user, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenDeleteUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    // When & Then
    service.deleteUser(userEntity.getId(), new Context());
  }

  @Test
  public void whenDeleteUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.deleteUser(userEntity.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
  }
}
