from pathlib import Path

import pytest

from tests.e2e import base_e2e_cases

from . import assert_schema
from .base_e2e_test import BaseE2ETest


class TestE2EDeepAggregationChain(BaseE2ETest):
    """Test E2E for DEEP_AGGREGATION_CHAIN testcase"""

    TESTCASE = base_e2e_cases.DEEP_AGGREGATION_CHAIN

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_ADDRESS (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            street TEXT,
            city TEXT
          );
          create table if not exists T_STUDENT (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT
          );
          create table if not exists T_STUDENT_ADDRESSES_TO_T_ADDRESS (
            student_id BIGINT not null,
            address_id BIGINT not null,
            primary key (student_id, address_id)
          );
          create table if not exists T_COURSE (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT
          );
          create table if not exists T_COURSE_STUDENTS_TO_T_STUDENT (
            course_id BIGINT not null,
            student_id BIGINT not null,
            primary key (course_id, student_id)
          );
          create table if not exists T_UNIVERSITY (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT
          );
          create table if not exists T_UNIVERSITY_COURSES_TO_T_COURSE (
            university_id BIGINT not null,
            course_id BIGINT not null,
            primary key (university_id, course_id)
          );
          alter table if exists T_STUDENT_ADDRESSES_TO_T_ADDRESS add constraint FK_T_STUDENT_ADDRESSES_TO_T_ADDRESS_STUDENT foreign key (student_id) references T_STUDENT(id);
          alter table if exists T_STUDENT_ADDRESSES_TO_T_ADDRESS add constraint FK_T_STUDENT_ADDRESSES_TO_T_ADDRESS_ADDRESS foreign key (address_id) references T_ADDRESS(id);
          alter table if exists T_COURSE_STUDENTS_TO_T_STUDENT add constraint FK_T_COURSE_STUDENTS_TO_T_STUDENT_COURSE foreign key (course_id) references T_COURSE(id);
          alter table if exists T_COURSE_STUDENTS_TO_T_STUDENT add constraint FK_T_COURSE_STUDENTS_TO_T_STUDENT_STUDENT foreign key (student_id) references T_STUDENT(id);
          alter table if exists T_UNIVERSITY_COURSES_TO_T_COURSE add constraint FK_T_UNIVERSITY_COURSES_TO_T_COURSE_UNIVERSITY foreign key (university_id) references T_UNIVERSITY(id);
          alter table if exists T_UNIVERSITY_COURSES_TO_T_COURSE add constraint FK_T_UNIVERSITY_COURSES_TO_T_COURSE_COURSE foreign key (course_id) references T_COURSE(id);
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
