from pathlib import Path

import pytest

from tests.e2e import base_e2e_cases

from . import assert_schema
from .base_e2e_test import BaseE2ETest


class TestE2EDefaultFlattening(BaseE2ETest):
    """Test E2E for DEFAULT_FLATTENING testcase"""

    TESTCASE = base_e2e_cases.DEFAULT_FLATTENING

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_FOO (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            a_int INTEGER,
            a_long BIGINT,
            a_float REAL,
            a_double DOUBLE PRECISION,
            a_string TEXT,
            a_fruit_field TEXT,
            b_int INTEGER,
            b_long BIGINT,
            b_float REAL,
            b_double DOUBLE PRECISION,
            b_string TEXT,
            b_fruit_field TEXT,
            boolean BOOLEAN,
            date DATE,
            datetime TIMESTAMP,
            object JSONB
          );
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
