from pathlib import Path

import pytest

from tests.e2e import base_e2e_cases

from . import assert_schema
from .base_e2e_test import BaseE2ETest


class TestE2ETwoParentOneChild(BaseE2ETest):
    """Test E2E for TWO_PARENT_ONE_CHILD testcase"""

    TESTCASE = base_e2e_cases.TWO_PARENT_ONE_CHILD

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
        create table if not exists T_FRUIT (
          id BIGINT generated by default as identity primary key,
          uid VARCHAR unique,
          iv INTEGER,
          name TEXT
        );
        create table if not exists T_FOO (
          id BIGINT generated by default as identity primary key,
          uid VARCHAR unique,
          iv INTEGER,
          name TEXT
        );
        create table if not exists T_FOO_BASKET_TO_T_FRUIT (
          foo_id BIGINT not null,
          fruit_id BIGINT not null,
          primary key (foo_id, fruit_id)
        );
        create table if not exists T_BAR (
          id BIGINT generated by default as identity primary key,
          uid VARCHAR unique,
          iv INTEGER,
          name TEXT
        );
        create table if not exists T_BAR_BASKET_TO_T_FRUIT (
          bar_id BIGINT not null,
          fruit_id BIGINT not null,
          primary key (bar_id, fruit_id)
        );
        alter table if exists T_FOO_BASKET_TO_T_FRUIT add constraint FK_T_FOO_BASKET_TO_T_FRUIT_FOO foreign key (foo_id) references T_FOO(id);
        alter table if exists T_FOO_BASKET_TO_T_FRUIT add constraint FK_T_FOO_BASKET_TO_T_FRUIT_FRUIT foreign key (fruit_id) references T_FRUIT(id);
        alter table if exists T_BAR_BASKET_TO_T_FRUIT add constraint FK_T_BAR_BASKET_TO_T_FRUIT_BAR foreign key (bar_id) references T_BAR(id);
        alter table if exists T_BAR_BASKET_TO_T_FRUIT add constraint FK_T_BAR_BASKET_TO_T_FRUIT_FRUIT foreign key (fruit_id) references T_FRUIT(id);
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
