from pathlib import Path

import pytest

from tests.e2e import base_e2e_cases

from . import assert_schema
from .base_e2e_test import BaseE2ETest


class TestE2ENestedBaseFlattening(BaseE2ETest):
    """Test E2E for NESTED_BASE_FLATTENING testcase"""

    TESTCASE = base_e2e_cases.NESTED_BASE_FLATTENING

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_COMPANY (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT,
            headquarters_street TEXT,
            headquarters_city TEXT,
            headquarters_contact_email TEXT,
            headquarters_contact_phone TEXT
          );
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
