/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.common.model;

import app.server.common.util.IdGenerator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Version;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.reflect.FieldUtils;

/**
 * MappedSuperclass for QSDL Object-Classes.
 */
@Slf4j
@MappedSuperclass
public abstract class AbstractPersistentObject {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    private Long id;

    @Column(unique = true, updatable = false)
    @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
    private String uid;

    @Version
    @JsonIgnore
    private Integer iv;

    /**
     * The internal numeric identifier.
     */
    public Long getId() {
        return id;
    }

    /**
     * The (external) unique identifier.
     */
    public String getUid() {
        return uid;
    }

    /**
     * Set the (external) unique identifier.
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * The version field.
     */
    public Integer getIv() {
        return iv;
    }

    @PrePersist
    private void ensureUid() {
        if (this.uid == null) {
            this.uid = IdGenerator.createId();
        }
    }

    /**
     * Copies the id, uid and iv field from another AbstractPersistentObject.
     */
    public void copyIdentity(AbstractPersistentObject o) {
        this.id = o.getId();
        this.uid = o.getUid();
        this.iv = o.getIv();
    }

    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (!(o instanceof AbstractPersistentObject)) {
            return false;
        }

        AbstractPersistentObject other = (AbstractPersistentObject) o;

        // if the uid is missing, return false
        if (uid == null) {
            return false;
        }

        // equivalence by uid
        return uid.equals(other.getUid());
    }

    public int hashCode() {
        if (uid != null) {
            return uid.hashCode();
        } else {
            return super.hashCode();
        }
    }
}
