/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import app.server.TestConfig;
import app.server.constant.ErrorCode;
import app.server.exception.AppException;
import app.server.model.AppError;
import app.server.util.Json;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.test.web.servlet.MockMvc;

/**
 * We mainly want to test our GlobalExceptionHandler here.
 * For this, it's enough to target a simple ping endpoint.
 */
@WebMvcTest(HomeController.class)
@Import(TestConfig.class)
class ControllerTest {

    String basePath = "/api/ping";

    @MockBean
    YAMLMapper mapper;

    @Autowired
    MockMvc mockMvc;

    @Test
    public void whenAppException_thenError() throws Exception {

        // Given
        when(mapper.readValue(anyString(), any(Class.class))).thenAnswer(invocation -> {
            throw new AppException(ErrorCode.ENTITY_NOT_FOUND);
        });

        // When
        String response = mockMvc.perform(get(basePath))
                .andExpect(status().isNotFound())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.serializer().fromJson(response, AppError.class);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    public void whenWrongMethod_thenError() throws Exception {

        // Given

        // When
        String response = mockMvc.perform(post(basePath))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.serializer().fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }
}
