/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.constant.ErrorCode;
import app.server.domain.ProjectRequest;
import app.server.domain.ProjectResponse;
import app.server.model.AppError;
import app.server.model.CursorPage;
import app.server.service.ProjectService;
import app.server.util.Json;
import java.util.Arrays;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(ProjectController.class)
@Import(TestConfig.class)
class ProjectControllerTest {

    @MockitoBean
    ProjectService service;

    @Value("${server.base-path:/}")
    String basePath;

    @Autowired
    MockMvc mockMvc;

    static Long one = 1L;

    @Test
    public void whenGetProjects_thenOk() throws Exception {

        // Given
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        CursorPage<ProjectResponse> ret = new CursorPage<ProjectResponse>(Arrays.asList(responseDto), null, null);

        when(service.getProjects(any(), any()))
                .thenReturn(ret);

        // When
        String response = mockMvc.perform(get(basePath + "/projects"))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(ret),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenCreateProject_thenOk() throws Exception {

        // Given
        ProjectRequest requestDto = TestUtils.getRandom(ProjectRequest.class);
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.createProject(any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(post(basePath + "/projects")
                        .content(Json.toString(requestDto))
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenCreateProjectWithInvalidPayload_thenError() throws Exception {

        // Given
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.createProject(any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(post(basePath + "/projects")
                .content("{}")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }

    @Test
    public void whenGetProject_thenOk() throws Exception {

        // Given
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.getProject(eq(one), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(get(basePath + "/projects/1"))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenReplaceProject_thenOk() throws Exception {

        // Given
        ProjectRequest requestDto = TestUtils.getRandom(ProjectRequest.class);
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.replaceProject(eq(one), any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(put(basePath + "/projects/1")
                        .content(Json.toString(requestDto))
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenReplaceProjectWithInvalidPayload_thenError() throws Exception {

        // Given
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.replaceProject(eq(one), any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(put(basePath + "/projects/1")
                .content("{}")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }

    @Test
    public void whenUpdateProject_thenOk() throws Exception {

        // Given
        ProjectRequest requestDto = TestUtils.getRandom(ProjectRequest.class);
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.updateProject(eq(one), any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(patch(basePath + "/projects/1")
                        .content(Json.toString(requestDto))
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenUpdateProjectWithInvalidPayload_thenError() throws Exception {

        // Given
        ProjectResponse responseDto = TestUtils.getRandom(ProjectResponse.class);

        when(service.updateProject(eq(one), any(), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(put(basePath + "/projects/1")
                .content("{}")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }

    @Test
    public void whenDeleteProject_thenOk() throws Exception {

        // Given

        // When
        mockMvc.perform(delete(basePath + "/projects/1"))
                .andExpect(status().isOk());

        // Then

    }
}
