/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.db;

import static org.junit.jupiter.api.Assertions.assertEquals;

import app.server.AbstractDataJpaTest;
import app.server.TestUtils;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.JsonUtil;
import app.server.project.db.ProjectEntity;
import app.server.project.db.ProjectRepository;
import app.server.project.db.QProjectEntity;
import app.server.user.db.RoleEntity;
import com.querydsl.core.BooleanBuilder;
import com.querydsl.core.types.dsl.BooleanExpression;
import java.util.List;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;

class ProjectRepositoryTest extends AbstractDataJpaTest {

    @Autowired
    ProjectRepository projectRepository;

    @Autowired
    TestEntityManager testEntityManager;

    public List<ProjectEntity> prepareData(int count) {

        List<ProjectEntity> testDatas = TestUtils.getRandomEntityWithNullId(ProjectEntity.class, count);

        for (ProjectEntity testData : testDatas) {
            testData.addToRoles(TestUtils.getRandomEntityWithNullId(RoleEntity.class));
        }

        projectRepository.saveAll(testDatas);

        // forces synchronization to DB
        // clears persistence context
        testEntityManager.flush();
        testEntityManager.clear();

        return projectRepository.findAll();
    }

    @Test
    public void whenSave_thenFind() throws Exception {

        // Given
        ProjectEntity testData = prepareData(1).get(0);

        // When
        ProjectEntity findData = projectRepository.findById(testData.getId()).orElse(null);

        TestUtils.copyAllIdentities(testData, findData);

        // Then
        JSONAssert.assertEquals(
                JsonUtil.toString(testData),
                new JSONObject(JsonUtil.toString(findData)),
                false);
    }

    @Test
    public void whenDelete_thenCountZero() throws Exception {

        // Given
        ProjectEntity testData = prepareData(1).get(0);

        // When
        projectRepository.delete(testData);

        // Then
        long count = projectRepository.count();
        assertEquals(0, count);
    }

    @Test
    public void whenCount_thenUseQuerie() throws Exception {

        // Given
        List<ProjectEntity> testData = prepareData(5);

        BooleanBuilder predicate = new BooleanBuilder();
        predicate.and(QProjectEntity.projectEntity.name.eq(testData.get(0).getName()));

        // When
        long count = projectRepository.count(predicate);

        // Then
        assertEquals(
                testData.stream()
                        .filter(d -> d.getName().equals(testData.get(0).getName()))
                        .count(),
                count);
    }

    @Test
    public void whenFindAll_thenPaginate() throws Exception {

        // Given
        List<ProjectEntity> testData = prepareData(5);

        // When
        String cursor = null;
        int idx = 0;

        do {
            CursorPageable pageable = new CursorPageable(cursor, 1, null);
            BooleanBuilder predicate = new BooleanBuilder();
            CursorPage<ProjectEntity> findData = projectRepository.findAll(predicate, pageable);

            cursor = findData.nextCursor();

            assertEquals(1, findData.count());

            idx++;
        } while (cursor != null);

        // Then
        assertEquals(5, idx);
    }
}
