/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.repository;

import app.server.domain.Ticket;

import org.springframework.stereotype.Repository;

@Repository
public interface TicketRepository extends AbstractRepository<Ticket, Long> {

}
