/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.repository;

import app.server.domain.UserEntity;

import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends AbstractRepository<UserEntity, Long> {

  public Optional<UserEntity> findByTicketsIdAndId(Long ticketId, Long id);

  public Optional<UserEntity> findByTicketsIdAndUid(Long ticketId, String uid);

}
