/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;

import app.server.AbstractDataJpaTest;
import app.server.TestUtils;
import app.server.domain.entity.*;
import app.server.domain.entity.UserEntity;
import app.server.model.*;
import app.server.repository.*;
import app.server.util.Json;
import com.querydsl.core.BooleanBuilder;
import java.util.List;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

class TicketRepositoryTest extends AbstractDataJpaTest {

  @Autowired
  TicketRepository ticketRepository;

  @Autowired
  TestEntityManager testEntityManager;

  public List<TicketEntity> prepareData(int count) {

    List<TicketEntity> testDatas = TestUtils.getRandomEntityWithNullId(TicketEntity.class, count);

    for (TicketEntity testData : testDatas) {
    }

    ticketRepository.saveAll(testDatas);

    // forces synchronization to DB
    // clears persistence context
    testEntityManager.flush();
    testEntityManager.clear();

    return ticketRepository.findAll();
  }

  @Test
  public void whenSave_thenFind() throws Exception {

    // Given
    TicketEntity testData = prepareData(1).get(0);

    // When
    TicketEntity findData = ticketRepository.findById(testData.getId()).orElse(null);

    TestUtils.copyAllIdentities(testData, findData);

    // Then
    JSONAssert.assertEquals(
        Json.serializer().toString(testData),
        new JSONObject(Json.serializer().toString(findData)),
        false);
  }

  @Test
  public void whenDelete_thenCountZero() throws Exception {

    // Given
    TicketEntity testData = prepareData(1).get(0);

    // When
    ticketRepository.delete(testData);

    // Then
    long count = ticketRepository.count();
    assertEquals(0, count);
  }

  @Test
  public void whenCount_thenUseQuerie() throws Exception {

    // Given
    List<TicketEntity> testData = prepareData(5);

    BooleanBuilder predicate = new BooleanBuilder();

    // When
    long count = ticketRepository.count(predicate);

    // Then
    assertEquals(5, count);
  }

  @Test
  public void whenFindAll_thenPaginate() throws Exception {

    // Given
    List<TicketEntity> testData = prepareData(5);

    // When
    String cursor = null;
    int idx = 0;

    do {
      CursorPageable pageable = new CursorPageable(cursor, 1, null);
      BooleanBuilder predicate = new BooleanBuilder();
      CursorPage<TicketEntity> findData = ticketRepository.findAll(predicate, pageable);

      cursor = findData.nextCursor();

      assertEquals(1, findData.count());

      idx++;
    } while (cursor != null);

    // Then
    assertEquals(5, idx);
  }
}
