/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.incident.sprints;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.test.model.*;


@Validated
@RequestMapping("${server.base-path:/}")
@Controller
public class SprintsController {

  private final NativeWebRequest request;

  @Autowired
  SprintsService sprintsService;

  @Autowired
  public SprintsController(NativeWebRequest request) {
    this.request = request;
  }

  public Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /milestones/{milestone_milestone}/sprints : List Sprints
   *
   * @param milestoneMilestone (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/milestones/{milestone_milestone}/sprints",
    produces = { "application/json" }
  )
  public ResponseEntity<SprintList> getSprints(@PathVariable("milestone_milestone") Long milestoneMilestone, ApiPageable pageable) throws Exception {
    SprintList response = sprintsService.getSprints(milestoneMilestone, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /milestones/{milestone_milestone}/sprints : Create a Sprint
   *
   * @param milestoneMilestone (required)
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/milestones/{milestone_milestone}/sprints",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Sprint> createSprint(@PathVariable("milestone_milestone") Long milestoneMilestone, @Valid @RequestBody Sprint body) throws Exception {
    Sprint response = sprintsService.createSprint(milestoneMilestone, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /milestones/{milestone_milestone}/sprints/{name} : Read the specified Sprint
   *
   * @param milestoneMilestone (required)
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/milestones/{milestone_milestone}/sprints/{name}",
    produces = { "application/json" }
  )
  public ResponseEntity<Sprint> getSprint(@PathVariable("milestone_milestone") Long milestoneMilestone, @PathVariable("name") Long name) throws Exception {
    Sprint response = sprintsService.getSprint(milestoneMilestone, name);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /milestones/{milestone_milestone}/sprints/{name} : Replace the specified Sprint
   *
   * @param milestoneMilestone (required)
   * @param name (required)
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PutMapping(
    value = "/milestones/{milestone_milestone}/sprints/{name}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Sprint> replaceSprint(@PathVariable("milestone_milestone") Long milestoneMilestone, @PathVariable("name") Long name, @Valid @RequestBody Sprint body) throws Exception {
    Sprint response = sprintsService.replaceSprint(milestoneMilestone, name, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /milestones/{milestone_milestone}/sprints/{name} : Update the specified Sprint
   *
   * @param milestoneMilestone (required)
   * @param name (required)
   * @param body (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PatchMapping(
    value = "/milestones/{milestone_milestone}/sprints/{name}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Sprint> updateSprint(@PathVariable("milestone_milestone") Long milestoneMilestone, @PathVariable("name") Long name, @Valid @RequestBody Sprint body) throws Exception {
    Sprint response = sprintsService.updateSprint(milestoneMilestone, name, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /milestones/{milestone_milestone}/sprints/{name} : Delete the specified Sprint
   *
   * @param milestoneMilestone (required)
   * @param name (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @DeleteMapping(
    value = "/milestones/{milestone_milestone}/sprints/{name}"
  )
  public ResponseEntity<Void> deleteSprint(@PathVariable("milestone_milestone") Long milestoneMilestone, @PathVariable("name") Long name) throws Exception {
    sprintsService.deleteSprint(milestoneMilestone, name);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
