/**
 * NOTE: This class was generated by QSDL.
 */
package app.server;

import java.util.TimeZone;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;

@SpringBootApplication
@ConfigurationPropertiesScan
public class SpringBootApp {

    public static void main(String[] args) {
        // set default JVM timezone before Spring starts
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));

        SpringApplication.run(SpringBootApp.class, args);
    }
}
