/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.common.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.dto.Ticket;
import app.server.common.dto.TicketRequest;
import app.server.common.model.AppError;
import app.server.common.model.CursorPage;
import app.server.common.service.TicketService;
import app.server.common.util.Json;
import app.server.common.util.JsonMergePatchConverter.MediaTypeExtension;
import java.util.Arrays;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(TicketController.class)
@Import(TestConfig.class)
class TicketControllerTest {

    @MockitoBean
    TicketService service;

    @Value("${server.base-path:/}")
    String basePath;

    @Autowired
    MockMvc mockMvc;

    static String one = "1";

    @Test
    public void whenGetTickets_thenOk() throws Exception {

        // Given
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        CursorPage<Ticket> ret = new CursorPage<Ticket>(Arrays.asList(responseDto), null, null);

        when(service.getTickets(any()))
                .thenReturn(ret);

        // When
        String response = mockMvc.perform(get(basePath + "/tickets"))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(ret),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenCreateTicket_thenOk() throws Exception {

        // Given
        TicketRequest requestDto = TestUtils.getRandom(TicketRequest.class);
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        when(service.createTicket(any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(post(basePath + "/tickets")
                        .content(Json.toString(requestDto))
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenCreateTicketWithInvalidPayload_thenError() throws Exception {

        // Given
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        when(service.createTicket(any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(post(basePath + "/tickets")
                .content("")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }

    @Test
    public void whenGetTicket_thenOk() throws Exception {

        // Given
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        when(service.getTicket(eq(one)))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(get(basePath + "/tickets/1"))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenUpdateTicket_thenOk() throws Exception {

        // Given
        TicketRequest requestDto = TestUtils.getRandom(TicketRequest.class);
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        when(service.getTicket(eq(one)))
                .thenReturn(responseDto);

        when(service.updateTicket(eq(one), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(patch(basePath + "/tickets/1")
                        .content(Json.toString(requestDto))
                        .contentType(MediaTypeExtension.APPLICATION_MERGE_PATCH))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        JSONAssert.assertEquals(
                Json.toString(responseDto),
                new JSONObject(response),
                false);
    }

    @Test
    public void whenUpdateTicketWithInvalidPayload_thenError() throws Exception {

        // Given
        Ticket responseDto = TestUtils.getRandom(Ticket.class);

        when(service.updateTicket(eq(one), any()))
                .thenReturn(responseDto);

        // When
        String response = mockMvc.perform(patch(basePath + "/tickets/1")
                .content("")
                .contentType(MediaTypeExtension.APPLICATION_MERGE_PATCH))
                .andExpect(status().isBadRequest())
                .andReturn()
                .getResponse()
                .getContentAsString();

        // Then
        AppError error = Json.fromJson(response, AppError.class);
        assertEquals(ErrorCode.BAD_REQUEST.code(), error.code);
        assertEquals(ErrorCode.BAD_REQUEST.message(), error.message);
        assertEquals(ErrorCode.BAD_REQUEST.status(), error.status);
    }

    @Test
    public void whenDeleteTicket_thenOk() throws Exception {

        // Given

        // When
        mockMvc.perform(delete(basePath + "/tickets/1"))
                .andExpect(status().isOk());

        // Then

    }
}
