/**
 * NOTE: This class was generated by QSDL.
 */

package app.server.service;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.config.ErrorCodes;
import app.server.domain.User;
import app.server.domain.entity.TicketEntity;
import app.server.domain.entity.UserEntity;
import app.server.domain.mapper.UserMapStruct;
import app.server.exception.AppException;
import app.server.model.*;
import app.server.repository.TicketRepository;
import app.server.repository.UserRepository;
import app.server.util.Json;

import com.fasterxml.jackson.databind.node.*;
import com.querydsl.core.types.Predicate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(SpringExtension.class)
@ExtendWith(MockitoExtension.class)
@Import(TestConfig.class)
class UserServiceTest {

  @Mock
  UserRepository repository;

  @Mock
  UserMapStruct mockedMapper;

  @Mock
  TicketRepository ticketRepository;

  UserService service;

  @Autowired
  private UserMapStruct mapper;

  private static Long one = 1L;

  @BeforeEach
  void setUp() {
    service = new UserService(ticketRepository, repository, mockedMapper);
  }

  @Test
  void whenGetUsersForTicket_thenOk() throws Exception {

    // Given
    List<UserEntity> userEntityList = TestUtils.getRandomEntity(UserEntity.class, 5);
    List<User> userList = userEntityList.stream().map(mapper::toDto).toList();
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(one)))
        .thenReturn(Optional.of(testParent));

    when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
        .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6l));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(userList.get(0))
        .thenReturn(userList.get(1))
        .thenReturn(userList.get(2))
        .thenReturn(userList.get(3))
        .thenReturn(userList.get(4));

    // When
    CursorPage<User> response = service.getUsersForTicket(one, new CursorPageable(null, 5L, true), new Context());

    // Then
    assertEquals(5L, response.count());
    assertEquals(6L, response.totalCount());

    ArrayNode node1 = Json.serializer().nodeFromList(userList);
    ArrayNode node2 = Json.serializer().nodeFromList(response.items());
    assertEquals(node1, node2);
  }

  @Test
  void whenAddUserToTicket_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(testParent.getId())))
        .thenReturn(Optional.of(testParent));

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(null);

    // When
    service.addUserToTicket(testParent.getId(), userEntity.getId(), new Context());

    // Then

  }

  @Test
  void whenRemoveUserFromTicket_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    TicketEntity testParent = TestUtils.getRandomEntity(TicketEntity.class);

    when(ticketRepository.findById(eq(testParent.getId())))
        .thenReturn(Optional.of(testParent));

    when(repository.findByTicketsIdAndId(eq(testParent.getId()), eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(null);

    // When
    service.removeUserFromTicket(testParent.getId(), userEntity.getId(), new Context());

    // Then

  }

  @Test
  void whenGetUsers_thenOk() throws Exception {

    // Given
    List<UserEntity> userEntityList = TestUtils.getRandomEntity(UserEntity.class, 5);
    List<User> userList = userEntityList.stream().map(mapper::toDto).toList();

    when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
        .thenReturn(new CursorPage<UserEntity>(userEntityList, null, 6l));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(userList.get(0))
        .thenReturn(userList.get(1))
        .thenReturn(userList.get(2))
        .thenReturn(userList.get(3))
        .thenReturn(userList.get(4));

    // When
    CursorPage<User> response = service.getUsers(new CursorPageable(null, 5L, true), new Context());

    // Then
    assertEquals(5L, response.count());
    assertEquals(6L, response.totalCount());

    ArrayNode node1 = Json.serializer().nodeFromList(userList);
    ArrayNode node2 = Json.serializer().nodeFromList(response.items());
    assertEquals(node1, node2);
  }

  @Test
  void whenCreateUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(mockedMapper.toEntity(any(User.class)))
        .thenReturn(userEntity);

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.createUser(user, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(user);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  void whenGetUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.getUser(userEntity.getId(), new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(user);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenGetUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.getUser(userEntity.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenReplaceUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.replaceUser(userEntity.getId(), user, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(user);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.replaceUser(userEntity.getId(), user, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenUpdateUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    when(repository.save(eq(userEntity)))
        .thenReturn(userEntity);

    when(mockedMapper.toDto(any(UserEntity.class)))
        .thenReturn(user);

    // When
    User response = service.updateUser(userEntity.getId(), user, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(user);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenUpdateUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);
    User user = mapper.toDto(userEntity);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.updateUser(userEntity.getId(), user, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenDeleteUser_thenOk() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.of(userEntity));

    // When
    service.deleteUser(userEntity.getId(), new Context());

    // Then

  }

  @Test
  public void whenDeleteUserWithInvalidId_thenError() throws Exception {

    // Given
    UserEntity userEntity = TestUtils.getRandomEntity(UserEntity.class);

    when(repository.findById(eq(userEntity.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.deleteUser(userEntity.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

}
