/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.server.domain;

import com.test.server.model.*;
import com.test.server.util.Json;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;

import java.time.OffsetDateTime;
import java.util.*;

@Entity
public class Project extends AbstractPersistentObject {

  @NotNull
  @Size(min = 0, max = 255)
  @JsonProperty(value = "name", required = true)
  public String name;

  @Size(min = 0, max = 255)
  @JsonProperty(value = "description")
  public String description;

  @Size(min = 0, max = 255)
  @JsonProperty(value = "creation_by", access = JsonProperty.Access.READ_ONLY)
  public String creationBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "creation_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime creationDate;

  @Size(min = 0, max = 255)
  @JsonProperty(value = "last_update_by", access = JsonProperty.Access.READ_ONLY)
  public String lastUpdateBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "last_update_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime lastUpdateDate;

  @Convert(converter = com.test.server.util.NodeConverter.class)
  @Column(columnDefinition = "text")
  @JsonProperty(value = "meta_inf")
  public ObjectNode metaInf;

  @JsonProperty(value = "archive", access = JsonProperty.Access.WRITE_ONLY)
  public Boolean archive;

  @OneToMany(mappedBy = "project", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  @JsonIgnore
  public final Set<Role> roles = new LinkedHashSet<>();


  public void addToRoles(Role o) {
    o.project = this;
    this.roles.add(o);
  }

  public void removeFromRoles(Role o) {
    o.project = null;
    this.roles.remove(o);
  }


  public static Project fromJson(String json) throws Json.JsonException {
    return Json.serializer().fromJson(json, Project.class);
  }

}
