/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.server.domain;

import com.test.server.constant.*;
import com.test.server.model.*;
import com.test.server.util.Json;

import com.fasterxml.jackson.annotation.*;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;

import java.time.*;
import java.util.*;

@Entity
public class Ticket extends AbstractPersistentObject {

  @Size(min = 0, max = 255)
  @JsonProperty(value = "title")
  public String title;

  @Size(min = 0, max = 255)
  @JsonProperty(value = "body")
  public String body;

  @JsonProperty(value = "status")
  public Status status;

  @ManyToMany(mappedBy = "tickets", fetch = FetchType.LAZY)
  @JsonIgnore
  public final Set<User> users = new LinkedHashSet<>();


  @PreRemove
  private void preRemoveHook() {
    new LinkedHashSet<>(this.users).forEach(o -> o.removeFromTickets(this));
  }

  public void addToUsers(User o) {
    o.tickets.add(this);
    this.users.add(o);
  }

  public void removeFromUsers(User o) {
    o.tickets.remove(this);
    this.users.remove(o);
  }


  public static Ticket fromJson(String json) throws Json.JsonException {
    return Json.serializer().fromJson(json, Ticket.class);
  }

}
