/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.repository;

import com.test.domain.Project;

import org.springframework.stereotype.Repository;

@Repository
public interface ProjectRepository extends AbstractRepository<Project, Long> {

}
