/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.repository;

import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.test.model.*;

@Repository
public interface ProjectRepository extends JpaRepository<Project, Long> {

  @Query(value = "select * from PROJECT where ID < :#{#pageable.cursor} order by ID desc limit :#{#pageable.limit}", nativeQuery = true)
  public List<Project> findAll(@Param("pageable") ApiPageable pageable);

}