/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.repository;

import java.util.*;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.test.domain.*;
import com.test.model.ApiPageable;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {

  @Query(
      value = """

          SELECT *
          FROM user
          WHERE 1 = 1
            AND ID < :#{#pageable.cursor}
          ORDER BY id DESC
          LIMIT :#{#pageable.limit}

          """,
      nativeQuery = true)
  public List<User> findAll(@Param("pageable") ApiPageable pageable);

  @Query(
      value = """

          SELECT *
          FROM user
            INNER JOIN ticket_to_user
            ON ticket_to_user.user_id = user.id
          WHERE 1 = 1
            AND ticket_to_user.ticket_id = :ticketId
            AND ID < :#{#pageable.cursor}
          ORDER BY id DESC
          LIMIT :#{#pageable.limit}

          """,
      nativeQuery = true)
  public List<User> findByTicketId(@Param("ticketId") Long ticketId, @Param("pageable") ApiPageable pageable);

  @Modifying
  @Query(
      value = """

          DELETE
          FROM
            TICKET_to_USER
          WHERE 1 = 1
            AND USER_id = :id

          """,
      nativeQuery = true)
  public void removeRelations(@Param("id") Long id);

}