/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.constant;

public final class Constant {

    private Constant() {
        // not called
    }

    public static final int CURSOR_DEFAULT = 100;
    public static final int CURSOR_MIN = 1;
    public static final int CURSOR_MAX = 1000;
}
