/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.api;

import app.server.common.api.BaseController;
import app.server.common.constants.*;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Validator;
import app.server.project.api.ProjectApi;
import app.server.project.dto.*;
import app.server.project.service.ProjectService;
import java.util.List;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import tools.jackson.databind.node.ObjectNode;

@Controller
@AllArgsConstructor
public class ProjectController extends BaseController implements ProjectApi {

    final ProjectService projectService;

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<CursorPage<ProjectResponse>> getProjects(CursorPageable pageable) {
        CursorPage<ProjectResponse> response = projectService.getProjects(pageable, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<ProjectResponse> createProject(ProjectRequest body) {
        Validator.validate(body);
        ProjectResponse response = projectService.createProject(body, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<ProjectResponse> getProject(Long id) {
        ProjectResponse response = projectService.getProject(id, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<ProjectResponse> replaceProject(Long id, ProjectRequest body) {
        Validator.validate(body);
        ProjectResponse response = projectService.replaceProject(id, body, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<ProjectResponse> updateProject(Long id, ProjectRequest body) {
        Validator.validateExRequired(body);
        ProjectResponse response = projectService.updateProject(id, body, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> deleteProject(Long id) {
        projectService.deleteProject(id, super.getContext());
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
