/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.db;

import static org.junit.jupiter.api.Assertions.assertEquals;

import app.server.AbstractDataJpaTest;
import app.server.TestUtils;
import app.server.common.db.*;
import app.server.common.db.TicketEntity;
import app.server.common.db.TicketRepository;
import app.server.common.model.*;
import app.server.common.util.Json;
import app.server.user.db.*;
import com.querydsl.core.BooleanBuilder;
import com.querydsl.core.types.dsl.BooleanExpression;
import java.util.List;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;

class UserRepositoryTest extends AbstractDataJpaTest {

    @Autowired
    TicketRepository ticketRepository;

    @Autowired
    UserRepository userRepository;

    @Autowired
    TestEntityManager testEntityManager;

    public List<UserEntity> prepareData(int count) {

        List<UserEntity> testDatas = TestUtils.getRandomEntityWithNullId(UserEntity.class, count);

        TicketEntity ticket = ticketRepository.save(TestUtils.getRandomEntityWithNullId(TicketEntity.class));

        for (UserEntity testData : testDatas) {
            testData.addToTickets(ticket);
        }

        userRepository.saveAll(testDatas);

        // forces synchronization to DB
        // clears persistence context
        testEntityManager.flush();
        testEntityManager.clear();

        return userRepository.findAll();
    }

    @Test
    public void whenSave_thenFind() throws Exception {

        // Given
        UserEntity testData = prepareData(1).get(0);

        // When
        UserEntity findData = userRepository.findById(testData.getId()).orElse(null);

        TestUtils.copyAllIdentities(testData, findData);

        // Then
        JSONAssert.assertEquals(
                Json.toString(testData),
                new JSONObject(Json.toString(findData)),
                false);
    }

    @Test
    public void whenDelete_thenCountZero() throws Exception {

        // Given
        UserEntity testData = prepareData(1).get(0);

        // When
        userRepository.delete(testData);

        // Then
        long count = userRepository.count();
        assertEquals(0, count);
    }

    @Test
    public void whenCount_thenUseQuerie() throws Exception {

        // Given
        List<UserEntity> testData = prepareData(5);

        BooleanBuilder predicate = new BooleanBuilder();

        // When
        long count = userRepository.count(predicate);

        // Then
        assertEquals(5, count);
    }

    @Test
    public void whenFindAll_thenPaginate() throws Exception {

        // Given
        List<UserEntity> testData = prepareData(5);

        // When
        String cursor = null;
        int idx = 0;

        do {
            CursorPageable pageable = new CursorPageable(cursor, 1, null);
            BooleanBuilder predicate = new BooleanBuilder();
            CursorPage<UserEntity> findData = userRepository.findAll(predicate, pageable);

            cursor = findData.nextCursor();

            assertEquals(1, findData.count());

            idx++;
        } while (cursor != null);

        // Then
        assertEquals(5, idx);
    }

    @Test
    public void whenCountByTicket_thenUseQuerie() throws Exception {

        // Given
        UserEntity testData = prepareData(5).get(0);
        TicketEntity parent = testData.getTickets().toArray(new TicketEntity[0])[0];

        BooleanExpression expression = QUserEntity.userEntity.tickets.any().id.eq(parent.getId());
        BooleanBuilder predicate = new BooleanBuilder(expression);

        // When
        long count = userRepository.count(predicate);

        // Then
        assertEquals(5, count);
    }

    @Test
    public void whenFindAllByTicket_thenPaginate() throws Exception {

        // Given
        Long parentId = prepareData(5)
                .get(0)
                .getTickets()
                .toArray(new TicketEntity[0])[0]
                .getId();

        // When
        String cursor = null;
        int idx = 0;

        do {
            CursorPageable pageable = new CursorPageable(cursor, 1, null);
            BooleanExpression expression = QUserEntity.userEntity.tickets.any().id.eq(parentId);
            BooleanBuilder predicate = new BooleanBuilder(expression);
            CursorPage<UserEntity> findData = userRepository.findAll(predicate, pageable);

            cursor = findData.nextCursor();

            assertEquals(1, findData.count());

            idx++;
        } while (cursor != null);

        // Then
        assertEquals(5, idx);
    }

    @Test
    public void whenUnlinkFromLinkedTicket_thenStillExist() throws Exception {

        // Given
        UserEntity testData = prepareData(1).get(0);
        TicketEntity parent = testData.getTickets().toArray(new TicketEntity[0])[0];

        // When
        testData.removeFromTickets(parent);
        userRepository.save(testData);

        // Then
        BooleanExpression expression = QUserEntity.userEntity.tickets.any().id.eq(parent.getId());
        BooleanBuilder predicate = new BooleanBuilder(expression);

        assertEquals(0, userRepository.count(predicate));
        assertEquals(true, userRepository.existsById(testData.getId()));
        assertEquals(true, ticketRepository.existsById(parent.getId()));
    }

    @Test
    public void whenDeleteFromLinkedTicket_thenStillExistA() throws Exception {

        // Given
        UserEntity testData = prepareData(1).get(0);
        TicketEntity parent = testData.getTickets().toArray(new TicketEntity[0])[0];

        // When
        userRepository.delete(testData);

        // Then
        BooleanExpression expression =QUserEntity.userEntity.tickets.any().id.eq(parent.getId());
        BooleanBuilder predicate = new BooleanBuilder(expression);

        assertEquals(0, userRepository.count(predicate));
        assertEquals(false, userRepository.existsById(testData.getId()));
        assertEquals(true, ticketRepository.existsById(parent.getId()));
    }

    @Test
    public void whenDeleteFromLinkedTicket_thenStillExistB() throws Exception {

        // Given
        UserEntity testData = prepareData(1).get(0);
        TicketEntity parent = testData.getTickets().toArray(new TicketEntity[0])[0];

        // When
        ticketRepository.delete(parent);

        // Then
        BooleanExpression expression = QUserEntity.userEntity.tickets.any().id.eq(parent.getId());
        BooleanBuilder predicate = new BooleanBuilder(expression);

        assertEquals(0, userRepository.count(predicate));
        assertEquals(true, userRepository.existsById(testData.getId()));
        assertEquals(false, ticketRepository.existsById(parent.getId()));
    }
}
