/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.common.api;

import app.server.common.constants.*;
import app.server.common.dto.*;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.List;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping("${server.base-path:/api/v1}")
@Controller
public interface TicketApi {

  /**
   * GET /tickets : getTickets
   *
   * List Tickets
   */
  @GetMapping(
      value = "/tickets",
      produces = {"application/json"}
  )
  default ResponseEntity<CursorPage<Ticket>> getTickets(CursorPageable pageable) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * POST /tickets : createTicket
   *
   * Create a Ticket
   */
  @PostMapping(
      value = "/tickets",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Ticket> createTicket(@RequestBody Ticket body) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * GET /tickets/{id} : getTicket
   *
   * Read the specified Ticket
   */
  @GetMapping(
      value = "/tickets/{id}",
      produces = {"application/json"}
  )
  default ResponseEntity<Ticket> getTicket(@PathVariable("id") Long id) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * PUT /tickets/{id} : replaceTicket
   *
   * Replace the specified Ticket
   */
  @PutMapping(
      value = "/tickets/{id}",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Ticket> replaceTicket(@PathVariable("id") Long id, @RequestBody Ticket body) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * PATCH /tickets/{id} : updateTicket
   *
   * Update the specified Ticket
   */
  @PatchMapping(
      value = "/tickets/{id}",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Ticket> updateTicket(@PathVariable("id") Long id, @RequestBody Ticket body) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * DELETE /tickets/{id} : deleteTicket
   *
   * Delete the specified Ticket
   */
  @DeleteMapping(
      value = "/tickets/{id}"
  )
  default ResponseEntity<Void> deleteTicket(@PathVariable("id") Long id) {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
