/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain;

import app.server.model.*;

import com.fasterxml.jackson.annotation.*;

import javax.persistence.*;
import javax.validation.constraints.*;

@Entity
public class Role extends AbstractPersistentObject {

  @NotNull
  @Size(min = 0, max = 255)
  @JsonProperty(value = "name", required = true)
  public String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "project_id")
  @JsonIgnore
  public Project project;


}
