/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.util;

import java.util.UUID;

public final class IdGenerator {

    private IdGenerator() {}

    public static String createId() {
        UUID uuid = UUID.randomUUID();
        return uuid.toString();
    }
}
