/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.controller;

import app.server.api.DefaultApi;
import app.server.domain.*;
import app.server.model.*;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;


@Validated
@Controller
public class DefaultController extends BaseController implements DefaultApi {

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<ObjectNode> submitQury(ObjectNode body) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<ObjectNode> action(BaseType arg1) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

}
