/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.controller;

import app.server.api.ProjectApi;
import app.server.domain.*;
import app.server.model.*;
import app.server.service.ProjectService;
import app.server.util.Validator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;

import java.util.*;

@Validated
@Controller
public class ProjectController extends BaseController implements ProjectApi {

  @Autowired
  ProjectService projectService;

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<CursorPage> getProjects(CursorPageable pageable) throws Exception {
    CursorPage response = projectService.getProjects(pageable, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Project> createProject(Project body) throws Exception {
    Project response = projectService.createProject(body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Project> getProject(Long id) throws Exception {
    Project response = projectService.getProject(id, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Project> replaceProject(Long id, Project body) throws Exception {
    Project response = projectService.replaceProject(id, body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Project> updateProject(Long id, Project body) throws Exception {
    Validator.validateExRequired(body);
    Project response = projectService.updateProject(id, body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Void> deleteProject(Long id) throws Exception {
    projectService.deleteProject(id, super.getContext());
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
