/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.controller;

import app.server.api.RoleApi;
import app.server.domain.*;
import app.server.model.*;
import app.server.service.RoleService;
import app.server.util.Validator;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;


@Validated
@Controller
public class RoleController extends BaseController implements RoleApi {

  @Autowired
  RoleService roleService;

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<CursorPage> getRoles(Long projectId, CursorPageable pageable) {
    CursorPage response = roleService.getRoles(projectId, pageable, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Role> createRole(Long projectId, Role body) {
    Role response = roleService.createRole(projectId, body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Role> getRole(Long projectId, Long id) {
    Role response = roleService.getRole(projectId, id, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Role> replaceRole(Long projectId, Long id, Role body) {
    Role response = roleService.replaceRole(projectId, id, body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Role> updateRole(Long projectId, Long id, Role body) {
    Validator.validateExRequired(body);
    Role response = roleService.updateRole(projectId, id, body, super.getContext());
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public ResponseEntity<Void> deleteRole(Long projectId, Long id) {
    roleService.deleteRole(projectId, id, super.getContext());
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
