create table if not exists T_PROJECT (
  id BIGINT generated by default as identity primary key,
  uid VARCHAR unique,
  iv INTEGER,
  name TEXT not null,
  description TEXT,
  creation_by TEXT,
  creation_date DATE,
  last_update_by TEXT,
  last_update_date TIMESTAMP,
  meta_inf JSONB,
  archive BOOLEAN
);

create table if not exists T_ROLE (
  id BIGINT generated by default as identity primary key,
  uid VARCHAR unique,
  iv INTEGER,
  name TEXT not null,
  roles_project_id BIGINT
);

create table if not exists T_USER (
  id BIGINT generated by default as identity primary key,
  uid VARCHAR unique,
  iv INTEGER,
  name TEXT not null,
  count INTEGER,
  mail TEXT unique
);

create table if not exists T_TICKET (
  id BIGINT generated by default as identity primary key,
  uid VARCHAR unique,
  iv INTEGER,
  number INTEGER,
  title TEXT,
  body TEXT,
  status TEXT check (status in ('OPEN', 'TO_DO', 'CLOSED'))
);

create table if not exists T_TICKET_TO_T_USER (
  ticket_id BIGINT not null,
  user_id BIGINT not null,
  primary key (ticket_id, user_id)
);

alter table if exists T_ROLE add constraint FK_T_ROLE_ROLES_PROJECT foreign key (roles_project_id) references T_PROJECT(id);
alter table if exists T_TICKET_TO_T_USER add constraint FK_T_TICKET_TO_T_USER_TICKET foreign key (ticket_id) references T_TICKET(id);
alter table if exists T_TICKET_TO_T_USER add constraint FK_T_TICKET_TO_T_USER_USER foreign key (user_id) references T_USER(id);
