/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.constant.ErrorCode;
import app.server.domain.Role;
import app.server.domain.RoleRequest;
import app.server.domain.entity.ProjectEntity;
import app.server.domain.entity.RoleEntity;
import app.server.domain.mapper.RoleMapper;
import app.server.exception.AppException;
import app.server.model.AppError;
import app.server.model.CursorPage;
import app.server.model.CursorPageable;
import app.server.repository.ProjectRepository;
import app.server.repository.RoleRepository;
import app.server.util.Json;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class RoleServiceTest {

    @MockitoBean
    RoleRepository repository;

    @MockitoBean
    ProjectRepository projectRepository;

    RoleService service;

    @Autowired
    RoleMapper mapper;

    static Long one = 1L;

    @BeforeEach
    void setUp() {
        service = new RoleService(projectRepository, repository, mapper);
    }

    @Test
    void whenGetRoles_thenOk() throws Exception {

        // Given
        List<RoleEntity> roleEntityList = TestUtils.getRandom(RoleEntity.class, 5);
        List<Role> roleList = roleEntityList.stream().map(mapper::toResponse).toList();
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<RoleEntity>(roleEntityList, null, 6L));

        // When
        CursorPage<Role> response = service.getRoles(one, new CursorPageable(null, 5, true));

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(roleList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenCreateRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        RoleRequest roleRequest = TestUtils.getRandom(RoleRequest.class);
        Role roleResponse = mapper.toResponse(roleEntity);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.save(any(RoleEntity.class)))
                .thenReturn(roleEntity);

        // When
        Role response = service.createRole(one, roleRequest);

        // Then
        JSONAssert.assertEquals(
                Json.toString(roleResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    void whenGetRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        Role roleResponse = mapper.toResponse(roleEntity);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        // When
        Role response = service.getRole(one, roleEntity.getId());

        // Then
        JSONAssert.assertEquals(
                Json.toString(roleResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenGetRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.getRole(one, roleEntity.getId());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenUpdateRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        RoleRequest roleRequest = TestUtils.getRandom(RoleRequest.class);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        when(repository.save(eq(roleEntity)))
                .thenReturn(roleEntity);

        // When
        Role response = service.updateRole(one, roleEntity.getId(), roleRequest);

        // Then
        Role roleResponse = mapper.toResponse(roleEntity);
        JSONAssert.assertEquals(
                Json.toString(roleResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenUpdateRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        RoleRequest roleRequest = TestUtils.getRandom(RoleRequest.class);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.updateRole(one, roleEntity.getId(), roleRequest);
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenDeleteRole_thenOk() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.of(roleEntity));

        // When & Then
        service.deleteRole(one, roleEntity.getId());
    }

    @Test
    public void whenDeleteRoleWithInvalidId_thenError() throws Exception {

        // Given
        RoleEntity roleEntity = TestUtils.getRandom(RoleEntity.class);
        ProjectEntity testParent = TestUtils.getRandom(ProjectEntity.class);

        when(projectRepository.findById(eq(one)))
                .thenReturn(Optional.of(testParent));

        when(repository.findByProjectIdAndId(eq(testParent.getId()), eq(roleEntity.getId())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.deleteRole(one, roleEntity.getId());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }
}
