from pathlib import Path

import pytest

from tests.e2e import assert_schema
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EComplexMixedBaseObjectArrays(BaseE2ETest):
    """Test E2E for COMPLEX_MIXED_BASE_OBJECT_ARRAYS testcase"""

    TESTCASE = """\
      base Address {
        street: String
        city: String
      }
      base Metadata {
        key: String
        value: String
      }
      type Department {
        name: String
      }
      type Employee {
        name: String
        homeAddress: Address
        workAddress: Address @opaque
        metadata: [Metadata]
        department: Department
        skills: [String]
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_DEPARTMENT (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT
          );
          create table if not exists T_EMPLOYEE (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT,
            home_address_street TEXT,
            home_address_city TEXT,
            work_address JSONB,
            metadata JSONB,
            department_department_id BIGINT unique,
            skills TEXT []
          );
          alter table if exists T_EMPLOYEE add constraint FK_T_EMPLOYEE_DEPARTMENT foreign key (department_department_id) references T_DEPARTMENT(id);
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
