from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EMixedBaseAndObjectFields(BaseE2ETest):
    """Test E2E for MIXED_BASE_AND_OBJECT_FIELDS testcase"""

    TESTCASE = """\
      base Address {
        street: String
        city: String
      }
      type Manager {
        name: String
      }
      type Employee {
        name: String
        homeAddress: Address
        manager: Manager
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            CREATE TABLE IF NOT EXISTS t_manager (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uid VARCHAR UNIQUE,
              iv INTEGER,
              creation_date TIMESTAMP NOT NULL,
              modification_date TIMESTAMP,
              name TEXT
            );

            CREATE TABLE IF NOT EXISTS t_employee (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uid VARCHAR UNIQUE,
              iv INTEGER,
              creation_date TIMESTAMP NOT NULL,
              modification_date TIMESTAMP,
              name TEXT,
              home_address_street TEXT,
              home_address_city TEXT,
              manager_manager_id BIGINT
            );

            ALTER TABLE IF EXISTS t_employee ADD CONSTRAINT fk_t_employee_manager FOREIGN KEY (manager_manager_id) REFERENCES t_manager(id);
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        schemas = openapi_schema["components"]["schemas"]

        employee = schemas["Employee"]["properties"]
        assert employee["homeAddress"]["$ref"] == "#/components/schemas/Address"
        assert employee["manager"]["$ref"] == "#/components/schemas/Manager"
        assert schemas["Address"]["properties"]["street"]["type"] == "string"
        assert schemas["Manager"]["properties"]["name"]["type"] == "string"

    def test_spring(self, srcgen: Path) -> None:
        src_root = srcgen / "src" / "main" / "java"

        entity_files = list(src_root.rglob("EmployeeEntity.java"))
        assert len(entity_files) == 1
        entity_content = entity_files[0].read_text(encoding="utf-8")
        assert "private String homeAddressStreet;" in entity_content
        assert "private String homeAddressCity;" in entity_content
        assert "@OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)" in entity_content
        assert "private ManagerEntity manager;" in entity_content

        request_files = list(src_root.rglob("EmployeeRequest.java"))
        assert len(request_files) == 1
        request_content = request_files[0].read_text(encoding="utf-8")
        assert "Address homeAddress" in request_content
        assert "ManagerRequest manager" in request_content

        mapper_files = list(src_root.rglob("EmployeeMapper.java"))
        assert len(mapper_files) == 1
        mapper_content = mapper_files[0].read_text(encoding="utf-8")
        assert "uses = { ManagerMapper.class }" in mapper_content
        assert '@Mapping(target = "homeAddress.street", source = "homeAddressStreet")' in mapper_content
        assert "EmployeeEntity toEntity(EmployeeRequest dto);" in mapper_content

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn(srcgen)
