from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EMixedBaseAndObjectFields(BaseE2ETest):
    """Test E2E for MIXED_BASE_AND_OBJECT_FIELDS testcase"""

    TESTCASE = """\
      base Address {
        street: String
        city: String
      }
      type Manager {
        name: String
      }
      type Employee {
        name: String
        homeAddress: Address
        manager: Manager
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            create table if not exists T_MANAGER (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT
            );

            create table if not exists T_EMPLOYEE (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT,
              home_address_street TEXT,
              home_address_city TEXT,
              manager_manager_id BIGINT
            );

            alter table if exists T_EMPLOYEE add constraint FK_T_EMPLOYEE_MANAGER foreign key (manager_manager_id) references T_MANAGER(id);
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn()
