from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EDefaultFlattening(BaseE2ETest):
    """Test E2E for DEFAULT_FLATTENING testcase"""

    TESTCASE = """\
        base Bar {
          string_field: String
        }
        base A {
          int_field: Int
          long_field: Long
        }
        base B extends A {
          float_field: Float
          double_field: Double
          string_field: String
          fruit: Bar
        }
        type Foo {
          nested_field_a: B
          nested_field_b: B
          boolean_field: Boolean
          date_field: Date
          datetime_field: Datetime
          object_field: Object
        }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_FOO (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            nested_field_a_int_field INTEGER,
            nested_field_a_long_field BIGINT,
            nested_field_a_float_field REAL,
            nested_field_a_double_field DOUBLE PRECISION,
            nested_field_a_string_field TEXT,
            nested_field_a_fruit_string_field TEXT,
            nested_field_b_int_field INTEGER,
            nested_field_b_long_field BIGINT,
            nested_field_b_float_field REAL,
            nested_field_b_double_field DOUBLE PRECISION,
            nested_field_b_string_field TEXT,
            nested_field_b_fruit_string_field TEXT,
            boolean_field BOOLEAN,
            date_field DATE,
            datetime_field TIMESTAMP,
            object_field JSONB
          );
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn()
