create table project (
  archive boolean,
  creation_date date,
  iv integer,
  id bigint generated by default as identity,
  last_update_date timestamp(6) with time zone,
  creation_by varchar(255),
  description varchar(255),
  last_update_by varchar(255),
  meta_inf text,
  name varchar(255) not null,
  uid varchar(255) unique,
  primary key (id)
);

create table role (
  iv integer,
  id bigint generated by default as identity,
  project_id bigint,
  name varchar(255) not null,
  uid varchar(255) unique,
  primary key (id),
  constraint FK82u6w3dkiooc7msaqc1e2cs0v foreign key (project_id) references project
);

create table ticket (
  iv integer,
  id bigint generated by default as identity,
  body varchar(255),
  status varchar(255) check (status in ('OPEN', 'TO_DO', 'CLOSED')),
  title varchar(255),
  uid varchar(255) unique,
  primary key (id)
);

create table "user" (
  count integer,
  iv integer,
  id bigint generated by default as identity,
  mail varchar(255) unique,
  name varchar(255) not null,
  uid varchar(255) unique,
  primary key (id)
);

create table ticket_to_user (
  ticket_id bigint not null,
  user_id bigint not null,
  primary key (ticket_id, user_id),
  constraint FK9kwopdmvcxcx9yols02jipejr foreign key (user_id) references "user",
  constraint FK89o4asc45g53i4abqcw9emcd7 foreign key (ticket_id) references ticket
);

