/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.jeasy.random.EasyRandom;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.test.config.Errors;
import com.test.domain.*;
import com.test.model.*;
import com.test.service.*;
import com.test.util.Json;

@WebMvcTest(RoleController.class)
@Import(com.test.TestConfig.class)
public class RoleControllerTest {

  @Autowired
  private EasyRandom easyRandom;

  @MockBean
  RoleService service;

  @Value("${server.base-path:/}")
  String basePath;

  @Autowired
  private MockMvc mockMvc;

  @Test
  public void whenGetRoles_thenOk() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    ObjectList ret = new ObjectList();
    ret.items = Arrays.asList(request);

    when(service.getRoles(any(), any()))
        .thenReturn(ret);

    // When
    String response = mockMvc.perform(get(basePath + "/projects/1/roles"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(ret);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1.get("items"), node2.get("items"));
  }

  @Test
  public void whenCreateRole_thenOk() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.createRole(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/projects/1/roles")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenCreateRoleWithInvalidPayload_thenError() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.createRole(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/projects/1/roles")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenGetRole_thenOk() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.getRole(eq(1l), eq(1l)))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(get(basePath + "/projects/1/roles/1"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceRole_thenOk() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.replaceRole(eq(1l), eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/projects/1/roles/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceRoleWithInvalidPayload_thenError() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.replaceRole(eq(1l), eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/projects/1/roles/1")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenUpdateRole_thenOk() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.updateRole(eq(1l), eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(patch(basePath + "/projects/1/roles/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenUpdateRoleWithInvalidPayload_thenError() throws Exception {

    // Given
    Role request = easyRandom.nextObject(Role.class);

    when(service.updateRole(eq(1l), eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/projects/1/roles/1")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenDeleteRole_thenOk() throws Exception {

    // Given

    // When
    mockMvc.perform(delete(basePath + "/projects/1/roles/1"))
        .andExpect(status().isOk());

    // Then

  }

}
