/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.jeasy.random.EasyRandom;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.test.TestConfig;
import com.test.config.Errors;
import com.test.domain.*;
import com.test.model.*;
import com.test.service.*;
import com.test.util.Json;

@WebMvcTest(TicketController.class)
@Import(TestConfig.class)
public class TicketControllerTest {

  @Autowired
  private EasyRandom easyRandom;

  @MockBean
  TicketService service;

  @Value("${server.base-path:/}")
  String basePath;

  @Autowired
  private MockMvc mockMvc;

  @Test
  public void whenGetTickets_thenOk() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    ObjectList ret = new ObjectList();
    ret.items = Arrays.asList(request);

    when(service.getTickets(any()))
        .thenReturn(ret);

    // When
    String response = mockMvc.perform(get(basePath + "/tickets"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(ret);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1.get("items"), node2.get("items"));
  }

  @Test
  public void whenCreateTicket_thenOk() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.createTicket(any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/tickets")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenCreateTicketWithInvalidPayload_thenError() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.createTicket(any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/tickets")
        .content("")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenGetTicket_thenOk() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.getTicket(eq(1l)))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(get(basePath + "/tickets/1"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceTicket_thenOk() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.replaceTicket(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/tickets/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceTicketWithInvalidPayload_thenError() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.replaceTicket(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/tickets/1")
        .content("")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenUpdateTicket_thenOk() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.updateTicket(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(patch(basePath + "/tickets/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenUpdateTicketWithInvalidPayload_thenError() throws Exception {

    // Given
    Ticket request = easyRandom.nextObject(Ticket.class);

    when(service.updateTicket(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/tickets/1")
        .content("")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(Errors.BAD_REQEST.code(), error.code);
    assertEquals(Errors.BAD_REQEST.message(), error.message);
    assertEquals(Errors.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenDeleteTicket_thenOk() throws Exception {

    // Given

    // When
    mockMvc.perform(delete(basePath + "/tickets/1"))
        .andExpect(status().isOk());

    // Then

  }

}
