/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.controller;

import com.test.TestConfig;
import com.test.config.ErrorCodes;
import com.test.domain.*;
import com.test.model.*;
import com.test.service.*;
import com.test.util.Json;

import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.*;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(UserController.class)
@Import(TestConfig.class)
public class UserControllerTest {

  @MockBean
  UserService service;

  @Value("${server.base-path:/}")
  String basePath;

  @Autowired
  private MockMvc mockMvc;

  @Test
  public void whenGetUsersForTicket_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    CursorPage ret = new CursorPage(Arrays.asList(request), null, null);

    when(service.getUsersForTicket(any(), any(), any()))
        .thenReturn(ret);

    // When
    String response = mockMvc.perform(get(basePath + "/tickets/1/users"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(ret);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1.get("items"), node2.get("items"));
  }

  @Test
  public void whenAddUserToTicket_thenOk() throws Exception {

    // Given

    // When
    mockMvc.perform(post(basePath + "/tickets/1/users/1/add"))
        .andExpect(status().isOk());

    // Then

  }

  @Test
  public void whenRemoveUserFromTicket_thenOk() throws Exception {

    // Given

    // When
    mockMvc.perform(post(basePath + "/tickets/1/users/1/remove"))
        .andExpect(status().isOk());

    // Then

  }

  @Test
  public void whenGetUsers_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    CursorPage ret = new CursorPage(Arrays.asList(request), null, null);

    when(service.getUsers(any(), any()))
        .thenReturn(ret);

    // When
    String response = mockMvc.perform(get(basePath + "/users"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(ret);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1.get("items"), node2.get("items"));
  }

  @Test
  public void whenCreateUser_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.createUser(any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/users")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenCreateUserWithInvalidPayload_thenError() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.createUser(any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(post(basePath + "/users")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(ErrorCodes.BAD_REQEST.code(), error.code);
    assertEquals(ErrorCodes.BAD_REQEST.message(), error.message);
    assertEquals(ErrorCodes.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenGetUser_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.getUser(eq(1l)))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(get(basePath + "/users/1"))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceUser_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.replaceUser(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/users/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceUserWithInvalidPayload_thenError() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.replaceUser(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/users/1")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(ErrorCodes.BAD_REQEST.code(), error.code);
    assertEquals(ErrorCodes.BAD_REQEST.message(), error.message);
    assertEquals(ErrorCodes.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenUpdateUser_thenOk() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.updateUser(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(patch(basePath + "/users/1")
        .content(Json.serializer().toString(request))
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isOk())
        .andReturn().getResponse().getContentAsString();

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromJson(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenUpdateUserWithInvalidPayload_thenError() throws Exception {

    // Given
    User request = TestConfig.getRandom(User.class);

    when(service.updateUser(eq(1l), any()))
        .thenReturn(request);

    // When
    String response = mockMvc.perform(put(basePath + "/users/1")
        .content("{}")
        .contentType(MediaType.APPLICATION_JSON))
        .andExpect(status().isBadRequest())
        .andReturn().getResponse().getContentAsString();

    // Then
    AppError error = AppError.fromJson(response);
    assertEquals(ErrorCodes.BAD_REQEST.code(), error.code);
    assertEquals(ErrorCodes.BAD_REQEST.message(), error.message);
    assertEquals(ErrorCodes.BAD_REQEST.status(), error.status);
  }

  @Test
  public void whenDeleteUser_thenOk() throws Exception {

    // Given

    // When
    mockMvc.perform(delete(basePath + "/users/1"))
        .andExpect(status().isOk());

    // Then

  }

}
