/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.incident.submit;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import org.jeasy.random.EasyRandom;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.test.model.*;

@Service
public class SubmitService {

  private static Logger log = LoggerFactory.getLogger(SubmitService.class.getSimpleName());

  @PostConstruct
  private void init() {

  }

  public QueryMachine submitQuery(Long buzzwordId, QueryMachine body) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    QueryMachine ret = easyRandom.nextObject(QueryMachine.class);

    return ret;
  }

}
