/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.config;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import org.springframework.boot.jackson.autoconfigure.JsonMapperBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import tools.jackson.databind.DeserializationFeature;
import tools.jackson.databind.SerializationFeature;

@Configuration
public class AppJacksonConfiguration {

    @Bean
    JsonMapperBuilderCustomizer jacksonCustomizer() {
        return builder -> {
            // Ignore null values when writing json.
            builder.changeDefaultPropertyInclusion(incl -> incl.withValueInclusion(Include.NON_NULL));

            builder.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            builder.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);

            // disable indent by default for the normal writer
            builder.disable(SerializationFeature.INDENT_OUTPUT);
        };
    }

    @Bean
    YAMLMapper yamlMapper() {
        return new YAMLMapper();
    }
}
