create table project (
  id bigint generated by default as identity (start with 1000),
  iv integer,
  uid varchar(255),
  archive boolean,
  creation_by varchar(255),
  creation_date timestamp,
  description varchar(255),
  last_update_by varchar(255),
  last_update_date timestamp,
  meta_inf text,
  name varchar(255) not null,
  primary key (id),
  constraint UK_9kxfbo6nxemjl9tf82wpxd0aj unique (uid)
);

create table role (
  id bigint generated by default as identity (start with 1000),
  iv integer,
  uid varchar(255),
  name varchar(255) not null,
  project_id bigint,
  primary key (id),
  constraint UK_1lrl2xbrerquux9fe9wmx1o3x unique (uid),
  constraint FK82u6w3dkiooc7msaqc1e2cs0v foreign key (project_id) references project
);

create table ticket (
  id bigint generated by default as identity (start with 1000),
  iv integer,
  uid varchar(255),
  body varchar(255),
  status integer,
  title varchar(255),
  primary key (id),
  constraint UK_bh2v9gyxpf6wg2qc5f8iw8c59 unique (uid)
);

create table "user" (
  id bigint generated by default as identity (start with 1000),
  iv integer,
  uid varchar(255),
  name varchar(255) not null,
  count integer,
  primary key (id),
  constraint UK_a7hlm8sj8kmijx6ucp7wfyt31 unique (uid)
);

create table ticket_to_user (
  user_id bigint not null,
  ticket_id bigint not null,
  primary key (user_id, ticket_id),
  constraint FK89o4asc45g53i4abqcw9emcd7 foreign key (ticket_id) references ticket,
  constraint FK9kwopdmvcxcx9yols02jipejr foreign key (user_id) references "user"
);