/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.model;

import app.server.util.Json;

public abstract class AbstractClass {

    @Override
    public String toString() throws Json.JsonException {
        return Json.serializer().toString(this);
    }

    public String toPrettyString() throws Json.JsonException {
        return Json.serializer().toPrettyString(this);
    }
}
