/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.model;

import app.server.util.TimeUtil;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.soabase.recordbuilder.core.RecordBuilder;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

@RecordBuilder
// @formatter:off
public record AppError(

    @JsonProperty(value = "code")
    String code,

    @JsonProperty(value = "message")
    String message,

    @JsonProperty(value = "status")
    Integer status,

    @JsonProperty(value = "path")
    String path,

    @JsonProperty(value = "timestamp")
    OffsetDateTime timestamp,

    @JsonProperty(value = "details")
    List<String> details

)
{
    public AppError() {
        this(null, null, null, null, TimeUtil.now(), new ArrayList<>());
    }

    public AppError(String code, String message, Integer status) {
        this(code, message, status, null, TimeUtil.now(), new ArrayList<>());
    }

    public AppError(String code, String message, Integer status, String detail) {
        this(code, message, status, null, TimeUtil.now(), List.of(detail));
    }

    public AppError(String code, String message, Integer status, List<String> details) {
        this(code, message, status, null, TimeUtil.now(), details);
    }
}
// @formatter:on
