/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.incident.tickets;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import org.jeasy.random.EasyRandom;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.test.model.*;

@Service
public class TicketsService {

  private static Logger log = LoggerFactory.getLogger(TicketsService.class.getSimpleName());

  @PostConstruct
  private void init() {

  }

  public TicketList getTickets(Long projectId, ApiPageable pageable) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    TicketList ret = easyRandom.nextObject(TicketList.class);

    return ret;
  }

  public Ticket createTicket(Long projectId, Ticket body) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    Ticket ret = easyRandom.nextObject(Ticket.class);

    return ret;
  }

  public Ticket getTicket(Long projectId, Long number) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    Ticket ret = easyRandom.nextObject(Ticket.class);

    return ret;
  }

  public Ticket replaceTicket(Long projectId, Long number, Ticket body) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    Ticket ret = easyRandom.nextObject(Ticket.class);

    return ret;
  }

  public Ticket updateTicket(Long projectId, Long number, Ticket body) throws Exception {

    // TODO: implement me

    EasyRandom easyRandom = new EasyRandom();
    Ticket ret = easyRandom.nextObject(Ticket.class);

    return ret;
  }

  public Void deleteTicket(Long projectId, Long number) throws Exception {

    // TODO: implement me

    return null;
  }

}
