/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.management.role;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.persistence.EntityNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.test.constants.AppError;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.model.*;

@Service
public class RoleService {

  private static Logger log = LoggerFactory.getLogger(RoleService.class.getSimpleName());


  @PostConstruct
  private void init() {

  }

  public RoleList getRolesForProject(Long projectId, ApiPageable pageable) throws Exception {

  return null;
  }

  public Role createRoleForProject(Long projectId, Role body) throws Exception {

  return null;
  }

  public Role getRoleForProject(Long projectId, Long role) throws Exception {

  return null;
  }

  public Role replaceRoleForProject(Long projectId, Long role, Role body) throws Exception {

  return null;
  }

  public Role updateRoleForProject(Long projectId, Long role, Role body) throws Exception {

  return null;
  }

  public Void deleteRoleForProject(Long projectId, Long role) throws Exception {

  return null;
  }

  public RoleList getRolesForSprint(Long sprintName, ApiPageable pageable) throws Exception {

  return null;
  }

  public Role createRoleForSprint(Long sprintName, Role body) throws Exception {

  return null;
  }

  public Role getRoleForSprint(Long sprintName, Long role) throws Exception {

  return null;
  }

  public Role replaceRoleForSprint(Long sprintName, Long role, Role body) throws Exception {

  return null;
  }

  public Role updateRoleForSprint(Long sprintName, Long role, Role body) throws Exception {

  return null;
  }

  public Void deleteRoleForSprint(Long sprintName, Long role) throws Exception {

  return null;
  }

}
