/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.common.util;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import java.util.ArrayList;
import java.util.List;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.node.ObjectNode;

/**
 * Attribute converter for lists of Jackson 3 {@link ObjectNode} values.
 *
 * <p>This is required with Spring Boot 4 since Hibernate does not support deserializing
 * the Jackson 3 {@link ObjectNode}, which would otherwise lead to:
 * {@code org.springframework.dao.InvalidDataAccessApiUsageException: Could not deserialize string to java type: class tools.jackson.databind.node.ObjectNode}
 */
@Converter
public final class ObjectNodeListConverter implements AttributeConverter<List<ObjectNode>, String> {

    @Override
    public String convertToDatabaseColumn(List<ObjectNode> attribute) {
        if (attribute == null) {
            return null;
        }

        try {
            return JsonUtil.toString(attribute);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to serialize List<ObjectNode> to JSON", e);
        }
    }

    @Override
    public List<ObjectNode> convertToEntityAttribute(String dbData) {
        if (dbData == null) {
            return null;
        }

        try {
            JsonNode node = JsonUtil.mapper().readTree(dbData);

            if (node == null || !node.isArray()) {
                throw new IllegalArgumentException(
                        "Expected a JSON array but got: " + (node == null ? "null" : node.getNodeType()));
            }

            List<ObjectNode> result = new ArrayList<>(node.size());

            for (JsonNode element : node) {
                if (element.isNull()) {
                    result.add(null);
                } else if (element.isObject()) {
                    result.add((ObjectNode) element);
                } else {
                    throw new IllegalArgumentException("Expected every array element to be a JSON object "
                            + "or null, but got: " + element.getNodeType());
                }
            }

            return result;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to deserialize JSON to List<ObjectNode>", e);
        }
    }
}
