/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain.mapper;

import app.server.domain.TicketRequest;
import app.server.domain.TicketResponse;
import app.server.domain.entity.TicketEntity;
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface TicketMapper {

    TicketRequest toRequest(TicketResponse dto);

    TicketResponse toResponse(TicketEntity entity);

    @Mapping(target = "uid", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "users", ignore = true)
    TicketEntity toEntity(TicketRequest dto);

    @InheritConfiguration(name = "toEntity")
    void update(TicketRequest source, @MappingTarget TicketEntity target);
}
