/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain.mapper;

import app.server.domain.UserRequest;
import app.server.domain.UserResponse;
import app.server.domain.entity.UserEntity;
import org.mapstruct.InheritConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserMapper {

    UserRequest toRequest(UserResponse dto);

    @Mapping(target = "tmp", ignore = true)
    UserResponse toResponse(UserEntity entity);

    @Mapping(target = "uid", ignore = true)
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "count", ignore = true)
    @Mapping(target = "tickets", ignore = true)
    UserEntity toEntity(UserRequest dto);

    @InheritConfiguration(name = "toEntity")
    void update(UserRequest source, @MappingTarget UserEntity target);
}
