/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import java.time.OffsetDateTime;
import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.node.ObjectNode;

import com.test.model.*;
import com.test.util.Json;

@Entity
public class BaseType extends AbstractPersistentBase {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @JsonProperty(value = "description")
  public String description;

  @JsonProperty(value = "creation_by", access = JsonProperty.Access.READ_ONLY)
  public String creationBy;

  @JsonProperty(value = "creation_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime creationDate;

  @JsonProperty(value = "last_update_by", access = JsonProperty.Access.READ_ONLY)
  public String lastUpdateBy;

  @JsonProperty(value = "last_update_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime lastUpdateDate;

  @Lob
  @Convert(converter = com.test.util.NodeConverter.class)
  @JsonProperty(value = "meta_inf")
  public ObjectNode metaInf;


  public static BaseType fromJson(String json) throws Json.JsonException {
    return Json.serializer().fromJson(json, BaseType.class);
  }

}
