/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import java.time.OffsetDateTime;
import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;
import org.springframework.format.annotation.DateTimeFormat;

@Embeddable
public class BaseType {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @JsonProperty(value = "description")
  public String description;

  @JsonProperty(value = "creation_by", access = JsonProperty.Access.READ_ONLY)
  public String creationBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "creation_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime creationDate;

  @JsonProperty(value = "last_update_by", access = JsonProperty.Access.READ_ONLY)
  public String lastUpdateBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "last_update_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime lastUpdateDate;

  @Column(columnDefinition = "BINARY(1048576)")
  @org.hibernate.annotations.Type(type = "serializable")
  @JsonProperty(value = "meta_inf")
  public Object metaInf;



  public static BaseType fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, BaseType.class);
  }

}
