/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import com.test.model.*;
import com.test.util.Json;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;

import java.time.OffsetDateTime;
import java.util.*;

@Entity
public class Role extends AbstractPersistentObject {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "project_id")
  @JsonIgnore
  public Project project;


  @PreRemove
  private void preRemoveHook() {
  }


  public static Role fromJson(String json) throws Json.JsonException {
    return Json.serializer().fromJson(json, Role.class);
  }

}
