/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;

import com.test.model.AbstractPersistentObject;

@Entity
public class Role extends AbstractPersistentObject {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name="project_id")
  @JsonIgnore
  public Project project;


  public static Role fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, Role.class);
  }

}
