/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import java.util.*;
import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;

import com.test.model.AbstractPersistentObject;

@Entity
public class Ticket extends AbstractPersistentObject {

  @JsonProperty(value = "title")
  public String title;

  @JsonProperty(value = "body")
  public String body;

  @JsonProperty(value = "status")
  public Status status;

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "ticket_to_user", joinColumns = @JoinColumn(name = "ticket_id"), inverseJoinColumns = @JoinColumn(name = "user_id"))
  @JsonIgnore
  public Set<User> users = new LinkedHashSet<>();


  public static Ticket fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, Ticket.class);
  }

}
