/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.domain;

import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;

import com.test.model.*;
import com.test.util.Json;

@Entity
public class User extends AbstractPersistentObject {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "ticket_to_user", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "ticket_id"))
  @JsonIgnore
  public final Set<Ticket> tickets = new LinkedHashSet<>();


  @PreRemove
  private void preRemoveHook() {
  }

  public void addToTickets(Ticket o) {
    o.users.add(this);
    this.tickets.add(o);
  }

  public void removeFromTickets(Ticket o) {
    o.users.remove(this);
    this.tickets.remove(o);
  }


  public static User fromJson(String json) throws Json.JsonException {
    return Json.serializer().fromJson(json, User.class);
  }

}
