/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain.entity;

import app.server.model.AbstractPersistentObject;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.*;

@Entity
@Table(name = "role")
public class RoleEntity extends AbstractPersistentObject {

  @NotNull
  public String name;

  @JsonIgnore
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "project_id")
  public ProjectEntity project;

}
