/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.server.service;

import com.test.server.TestConfig;
import com.test.server.config.ErrorCodes;
import com.test.server.domain.*;
import com.test.server.exception.AppException;
import com.test.server.model.*;
import com.test.server.repository.*;
import com.test.server.util.Json;

import com.fasterxml.jackson.databind.node.*;
import com.querydsl.core.types.Predicate;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.context.annotation.Import;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.util.LinkedMultiValueMap;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(SpringExtension.class)
@ExtendWith(MockitoExtension.class)
@Import(TestConfig.class)
public class ProjectServiceTest {

  @Mock
  private ProjectRepository repository;

  @InjectMocks
  ProjectService service;

  private static Long one = 1l;

  @Test
  void whenGetProjects_thenOk() throws Exception {

    // Given
    List<Project> request = TestConfig.getRandom(Project.class, 5);

    when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
        .thenReturn(new CursorPage(request, null, 6l));

    // When
    CursorPage response = service.getProjects(new CursorPageable(null, 5l, true), new Context());

    // Then
    assertEquals(5l, response.count());
    assertEquals(6l, response.totalCount());

    ArrayNode node1 = Json.serializer().nodeFromList(request);
    ArrayNode node2 = Json.serializer().nodeFromList(response.items());
    assertEquals(node1, node2);
  }

  @Test
  void whenCreateProject_thenOk() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.save(eq(request)))
        .thenReturn(request);

    // When
    Project response = service.createProject(request, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  void whenGetProject_thenOk() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.of(request));

    // When
    Project response = service.getProject(request.getId(), new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenGetProjectWithInvalidId_thenError() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.getProject(request.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenReplaceProject_thenOk() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.of(request));

    when(repository.save(eq(request)))
        .thenReturn(request);

    // When
    Project response = service.replaceProject(request.getId(), request, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenReplaceProjectWithInvalidId_thenError() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.replaceProject(request.getId(), request, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenUpdateProject_thenOk() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.of(request));

    when(repository.save(eq(request)))
        .thenReturn(request);

    // When
    Project response = service.updateProject(request.getId(), request, new Context());

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(request);
    ObjectNode node2 = Json.serializer().nodeFromObject(response);
    assertEquals(node1, node2);
  }

  @Test
  public void whenUpdateProjectWithInvalidId_thenError() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    when(repository.findById(eq(request.getId())))
        .thenReturn(Optional.ofNullable(null));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.updateProject(request.getId(), request, new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

  @Test
  void whenDeleteProject_thenOk() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    // When
    service.deleteProject(request.getId(), new Context());

    // Then

  }

  @Test
  public void whenDeleteProjectWithInvalidId_thenError() throws Exception {

    // Given
    Project request = TestConfig.getRandom(Project.class);

    doThrow(new EmptyResultDataAccessException(1))
        .when(repository).deleteById(eq(request.getId()));

    // When
    AppException thrown = assertThrows(AppException.class,
        () -> {
          service.deleteProject(request.getId(), new Context());
        });

    // Then
    AppError error = thrown.getAppError();
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.code(), error.code);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.message(), error.message);
    assertEquals(ErrorCodes.ENTITY_NOT_FOUND.status(), error.status);
  }

}
