from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EDeepCompositionChain(BaseE2ETest):
    """Test E2E for DEEP_COMPOSITION_CHAIN testcase"""

    TESTCASE = """\
      type Employee {
        name: String
        email: String
      }
      type Team {
        name: String
        members: [Employee] @composition
      }
      type Department {
        name: String
        teams: [Team] @composition
      }
      type Organization {
        name: String
        departments: [Department] @composition
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            create table if not exists T_EMPLOYEE (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT,
              email TEXT,
              members_team_id BIGINT
            );

            create table if not exists T_TEAM (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT,
              teams_department_id BIGINT
            );

            create table if not exists T_DEPARTMENT (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT,
              departments_organization_id BIGINT
            );

            create table if not exists T_ORGANIZATION (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT
            );

            alter table if exists T_EMPLOYEE add constraint FK_T_EMPLOYEE_MEMBERS_TEAM foreign key (members_team_id) references T_TEAM(id);
            alter table if exists T_TEAM add constraint FK_T_TEAM_TEAMS_DEPARTMENT foreign key (teams_department_id) references T_DEPARTMENT(id);
            alter table if exists T_DEPARTMENT add constraint FK_T_DEPARTMENT_DEPARTMENTS_ORGANIZATION foreign key (departments_organization_id) references T_ORGANIZATION(id);
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn()
