from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2ETwoParentOneChild(BaseE2ETest):
    """Test E2E for TWO_PARENT_ONE_CHILD testcase"""

    TESTCASE = """\
        type Fruit {
          name: String
        }
        type Foo {
          name: String
          basket: [Fruit] @composition
        }
        type Bar {
          name: String
          basket: [Fruit] @composition
        }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            create table if not exists T_FRUIT (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT,
              basket_foo_id BIGINT,
              basket_bar_id BIGINT
            );

            create table if not exists T_FOO (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT
            );

            create table if not exists T_BAR (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              name TEXT
            );

            alter table if exists T_FRUIT add constraint FK_T_FRUIT_BASKET_FOO foreign key (basket_foo_id) references T_FOO(id);
            alter table if exists T_FRUIT add constraint FK_T_FRUIT_BASKET_BAR foreign key (basket_bar_id) references T_BAR(id);
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn()
