from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EOneToMany(BaseE2ETest):
    """Test E2E for ONE_TO_MANY testcase"""

    TESTCASE = """\
        type User {
          primary_metric: [Metric]
          secondary_metric: [Metric]
        }
        type Metric {
          likes: Int
        }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            CREATE TABLE IF NOT EXISTS t_user (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uid VARCHAR UNIQUE,
              iv INTEGER,
              creation_date TIMESTAMP NOT NULL,
              modification_date TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS t_metric (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              uid VARCHAR UNIQUE,
              iv INTEGER,
              creation_date TIMESTAMP NOT NULL,
              modification_date TIMESTAMP,
              likes INTEGER,
              primary_metric_user_id BIGINT,
              secondary_metric_user_id BIGINT
            );

            ALTER TABLE IF EXISTS t_metric ADD CONSTRAINT fk_t_metric_primary_metric_user FOREIGN KEY (primary_metric_user_id) REFERENCES t_user(id);
            ALTER TABLE IF EXISTS t_metric ADD CONSTRAINT fk_t_metric_secondary_metric_user FOREIGN KEY (secondary_metric_user_id) REFERENCES t_user(id);
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        schemas = openapi_schema["components"]["schemas"]

        user_properties = schemas["User"]["properties"]
        assert user_properties["primary_metric"] == {
            "type": "array",
            "items": {"$ref": "#/components/schemas/Metric"},
        }
        assert user_properties["secondary_metric"] == {
            "type": "array",
            "items": {"$ref": "#/components/schemas/Metric"},
        }

        users = openapi_schema["paths"]["/users"]
        assert users["post"]["requestBody"]["content"]["application/json"]["schema"] == {
            "$ref": "#/components/schemas/User"
        }
        assert users["post"]["responses"]["200"]["content"]["application/json"]["schema"] == {
            "$ref": "#/components/schemas/User"
        }
        assert "/users/{user_id}/primary_metric" not in openapi_schema["paths"]
        assert "/users/{user_id}/secondary_metric" not in openapi_schema["paths"]

    def test_spring(self, srcgen: Path) -> None:
        src_root = srcgen / "src" / "main" / "java"

        user_entity = next(src_root.rglob("UserEntity.java")).read_text(encoding="utf-8")
        assert (
            '@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)\n    @JoinColumn(name = "primary_metric_user_id")'
            in user_entity
        )
        assert "private List<MetricEntity> primaryMetric;" in user_entity
        assert (
            '@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)\n    @JoinColumn(name = "secondary_metric_user_id")'
            in user_entity
        )
        assert "private List<MetricEntity> secondaryMetric;" in user_entity
        assert len(list(src_root.rglob("UserRepository.java"))) == 1

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn(srcgen)
