/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.common.dto;

import app.server.common.constants.Status;
import app.server.common.model.AbstractClass;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.validation.*;
import jakarta.validation.constraints.*;
import java.time.*;
import java.util.*;
import lombok.*;
import lombok.extern.jackson.Jacksonized;
@Getter
@Setter
@Builder
@Jacksonized
@EqualsAndHashCode(callSuper = false)
public class Ticket extends AbstractClass {

  @Min(0)
  @Max(Long.MAX_VALUE)
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @Min(0)
  @Max(Integer.MAX_VALUE)
  @Builder.Default
  @JsonProperty(value = "number")
  private Integer number = 42;

  @Size(min = 0, max = 255)
  @Builder.Default
  @JsonProperty(value = "title")
  private String title = "Witty Title";

  @Size(min = 0, max = 255)
  @JsonProperty(value = "body")
  private String body;

  @Builder.Default
  @JsonProperty(value = "status")
  private Status status = Status.OPEN;

}
