/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

import app.server.TestConfig;
import app.server.TestUtils;
import app.server.common.constants.ErrorCode;
import app.server.common.exception.AppException;
import app.server.common.model.AppError;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.Json;
import app.server.project.db.ProjectEntity;
import app.server.project.db.ProjectRepository;
import app.server.project.dto.ProjectRequest;
import app.server.project.dto.ProjectResponse;
import app.server.project.mapper.ProjectMapStruct;
import com.querydsl.core.types.Predicate;
import java.util.List;
import java.util.Optional;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.skyscreamer.jsonassert.JSONAssert;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@Import(TestConfig.class)
class ProjectServiceTest {

    @MockitoBean
    ProjectRepository repository;

    ProjectService service;

    @Autowired
    ProjectMapStruct mapper;

    @BeforeEach
    void setUp() {
        service = new ProjectService(repository, mapper);
    }

    @Test
    void whenGetProjects_thenOk() throws Exception {

        // Given
        List<ProjectEntity> projectEntityList = TestUtils.getRandom(ProjectEntity.class, 5);
        List<ProjectResponse> projectList = projectEntityList.stream().map(mapper::toResponse).toList();

        when(repository.findAll(any(Predicate.class), any(CursorPageable.class)))
                .thenReturn(new CursorPage<ProjectEntity>(projectEntityList, null, 6L));

        // When
        CursorPage<ProjectResponse> response = service.getProjects(new CursorPageable(null, 5, true), new Context());

        // Then
        assertEquals(5L, response.count());
        assertEquals(6L, response.totalCount());

        JSONAssert.assertEquals(
                Json.toString(projectList),
                new JSONArray(Json.toString(response.items())),
                false);
    }

    @Test
    void whenCreateProject_thenOk() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);
        ProjectRequest projectRequest = TestUtils.getRandom(ProjectRequest.class);
        ProjectResponse projectResponse = mapper.toResponse(projectEntity);

        when(repository.save(any(ProjectEntity.class)))
                .thenReturn(projectEntity);

        // When
        ProjectResponse response = service.createProject(projectRequest, new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(projectResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    void whenGetProject_thenOk() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);
        ProjectResponse projectResponse = mapper.toResponse(projectEntity);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.of(projectEntity));

        // When
        ProjectResponse response = service.getProject(projectEntity.getUid(), new Context());

        // Then
        JSONAssert.assertEquals(
                Json.toString(projectResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenGetProjectWithInvalidId_thenError() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.getProject(projectEntity.getUid(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenUpdateProject_thenOk() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);
        ProjectRequest projectRequest = TestUtils.getRandom(ProjectRequest.class);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.of(projectEntity));

        when(repository.save(eq(projectEntity)))
                .thenReturn(projectEntity);

        // When
        ProjectResponse response = service.updateProject(projectEntity.getUid(), projectRequest, new Context());

        // Then
        ProjectResponse projectResponse = mapper.toResponse(projectEntity);
        JSONAssert.assertEquals(
                Json.toString(projectResponse),
                new JSONObject(Json.toString(response)),
                false);
    }

    @Test
    public void whenUpdateProjectWithInvalidId_thenError() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);
        ProjectRequest projectRequest = TestUtils.getRandom(ProjectRequest.class);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.updateProject(projectEntity.getUid(), projectRequest, new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }

    @Test
    void whenDeleteProject_thenOk() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.of(projectEntity));

        // When & Then
        service.deleteProject(projectEntity.getUid(), new Context());
    }

    @Test
    public void whenDeleteProjectWithInvalidId_thenError() throws Exception {

        // Given
        ProjectEntity projectEntity = TestUtils.getRandom(ProjectEntity.class);

        when(repository.findByUid(eq(projectEntity.getUid())))
                .thenReturn(Optional.ofNullable(null));

        // When
        AppException thrown = assertThrows(AppException.class,
                () -> {
                    service.deleteProject(projectEntity.getUid(), new Context());
                });

        // Then
        AppError error = thrown.getAppError();
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.code(), error.code);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.message(), error.message);
        assertEquals(ErrorCode.ENTITY_NOT_FOUND.status(), error.status);
    }
}
