/**
 * NOTE: This class was generated by QSDL.
 */
package app.server;

import app.server.common.db.BaseRepositoryImpl;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@DataJpaTest
@Import(TestConfig.class)
@EnableJpaRepositories(
        basePackages = {"app.server.common.db", "app.server.custom.db", "app.server.project.db", "app.server.user.db"},
        repositoryBaseClass = BaseRepositoryImpl.class)
public abstract class AbstractDataJpaTest {}
