/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.api;

import app.server.domain.*;
import app.server.model.*;

import org.springframework.http.*;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;


@Validated
@RequestMapping("${server.base-path:/api/v1}")
@Controller
public interface ProjectApi {

  /**
   * GET /projects : List Projects
   */
  @GetMapping(
      value = "/projects",
      produces = {"application/json"}
  )
  default ResponseEntity<CursorPage> getProjects(CursorPageable pageable) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * POST /projects : Create a Project
   */
  @PostMapping(
      value = "/projects",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Project> createProject(@Valid @RequestBody Project body) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * GET /projects/{id} : Read the specified Project
   */
  @GetMapping(
      value = "/projects/{id}",
      produces = {"application/json"}
  )
  default ResponseEntity<Project> getProject(@PathVariable("id") Long id) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * PUT /projects/{id} : Replace the specified Project
   */
  @PutMapping(
      value = "/projects/{id}",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Project> replaceProject(@PathVariable("id") Long id, @Valid @RequestBody Project body) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * PATCH /projects/{id} : Update the specified Project
   */
  @PatchMapping(
      value = "/projects/{id}",
      produces = {"application/json"},
      consumes = {"application/json"}
  )
  default ResponseEntity<Project> updateProject(@PathVariable("id") Long id, @RequestBody Project body) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

  /**
   * DELETE /projects/{id} : Delete the specified Project
   */
  @DeleteMapping(
      value = "/projects/{id}"
  )
  default ResponseEntity<Void> deleteProject(@PathVariable("id") Long id) throws Exception {
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }

}
