from pathlib import Path

import pytest

from tests.e2e import assert_schema
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2EOneToOne(BaseE2ETest):
    """Test XXXX"""

    TESTCASE = """\
        type User {
          primary_metric: Metric
          secondary_metric: Metric
        }
        type Metric {
          likes: Int
        }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
            create table if not exists T_USER (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              primary_metric_metric_id BIGINT unique,
              secondary_metric_metric_id BIGINT unique
            );

            create table if not exists T_METRIC (
              id BIGINT generated by default as identity primary key,
              uid VARCHAR unique,
              iv INTEGER,
              likes INTEGER
            );

            alter table if exists T_USER add constraint FK_T_USER_PRIMARY_METRIC foreign key (primary_metric_metric_id) references T_METRIC(id);
            alter table if exists T_USER add constraint FK_T_USER_SECONDARY_METRIC foreign key (secondary_metric_metric_id) references T_METRIC(id);
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
