from pathlib import Path

import pytest

from tests.e2e import assert_schema
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2ENestedObjectRelationships(BaseE2ETest):
    """Test E2E for NESTED_OBJECT_RELATIONSHIPS testcase"""

    TESTCASE = """\
      type Country {
        name: String
      }
      type City {
        name: String
        country: Country
      }
      type Address {
        street: String
        city: City
      }
      type Company {
        name: String
        headquarters: Address
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_COUNTRY (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT
          );
          create table if not exists T_CITY (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT,
            country_country_id BIGINT unique
          );
          create table if not exists T_ADDRESS (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            street TEXT,
            city_city_id BIGINT unique
          );
          create table if not exists T_COMPANY (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            name TEXT,
            headquarters_address_id BIGINT unique
          );
          alter table if exists T_CITY add constraint FK_T_CITY_COUNTRY foreign key (country_country_id) references T_COUNTRY(id);
          alter table if exists T_ADDRESS add constraint FK_T_ADDRESS_CITY foreign key (city_city_id) references T_CITY(id);
          alter table if exists T_COMPANY add constraint FK_T_COMPANY_HEADQUARTERS foreign key (headquarters_address_id) references T_ADDRESS(id);
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
