/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.api;

import app.server.api.BaseController;
import app.server.api.TicketApi;
import app.server.domain.*;
import app.server.domain.mapper.TicketMapper;
import app.server.model.CursorPage;
import app.server.model.CursorPageable;
import app.server.service.TicketService;
import app.server.util.JsonMergePatchUtil;
import app.server.util.Validator;
import jakarta.json.JsonMergePatch;
import java.util.List;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import tools.jackson.databind.node.ObjectNode;

@Controller
@AllArgsConstructor
public class TicketController extends BaseController implements TicketApi {

    final TicketService ticketService;
    final TicketMapper ticketMapper;

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<CursorPage<Ticket>> getTickets(CursorPageable pageable) {
        CursorPage<Ticket> response = ticketService.getTickets(pageable);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Ticket> createTicket(TicketRequest request) {
        Validator.validate(request);
        Ticket response = ticketService.createTicket(request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Ticket> getTicket(Long id) {
        Ticket response = ticketService.getTicket(id);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Ticket> updateTicket(Long id, JsonMergePatch patch) {
        Ticket current = ticketService.getTicket(id);
        TicketRequest target = ticketMapper.toRequest(current);
        TicketRequest request = JsonMergePatchUtil.apply(patch, target);

        Validator.validate(request);
        Ticket response = ticketService.updateTicket(id, request);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> deleteTicket(Long id) {
        ticketService.deleteTicket(id);
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
