/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.api;

import app.server.api.BaseController;
import app.server.api.UserApi;
import app.server.constant.*;
import app.server.domain.*;
import app.server.domain.mapper.UserMapper;
import app.server.model.CursorPage;
import app.server.model.CursorPageable;
import app.server.service.UserService;
import app.server.util.JsonMergePatchUtil;
import app.server.util.Validator;
import jakarta.json.JsonMergePatch;
import java.util.List;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import tools.jackson.databind.node.ObjectNode;

@Controller
@AllArgsConstructor
public class UserController extends BaseController implements UserApi {

    final UserService userService;
    final UserMapper userMapper;

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<CursorPage<UserResponse>> getUsersForTicket(Long ticketId, CursorPageable pageable) {
        CursorPage<UserResponse> response = userService.getUsersForTicket(ticketId, pageable, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> addUserToTicket(Long ticketId, Long id) {
        userService.addUserToTicket(ticketId, id, super.getContext());
        return new ResponseEntity<>(HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> removeUserFromTicket(Long ticketId, Long id) {
        userService.removeUserFromTicket(ticketId, id, super.getContext());
        return new ResponseEntity<>(HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<CursorPage<UserResponse>> getUsers(CursorPageable pageable) {
        CursorPage<UserResponse> response = userService.getUsers(pageable, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<UserResponse> createUser(UserRequest body) {
        Validator.validate(body);
        UserResponse response = userService.createUser(body, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<UserResponse> getUser(Long id) {
        UserResponse response = userService.getUser(id, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<UserResponse> updateUser(Long id, JsonMergePatch patch) {
        UserResponse current = userService.getUser(id, super.getContext());
        UserRequest target = userMapper.toRequest(current);
        UserRequest request = JsonMergePatchUtil.apply(patch, target);

        Validator.validate(request);
        UserResponse response = userService.updateUser(id, request, super.getContext());
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * {@inheritDoc}.
     */
    @Override
    public ResponseEntity<Void> deleteUser(Long id) {
        userService.deleteUser(id, super.getContext());
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
