/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api.incident.milestone;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.test.model.*;
import com.test.util.Validator;


@Validated
@RequestMapping("${server.base-path:/}")
@Controller
public class MilestoneController {

  private final NativeWebRequest request;

  @Autowired
  MilestoneService milestoneService;

  @Autowired
  public MilestoneController(NativeWebRequest request) {
    this.request = request;
  }

  public Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /tickets/{ticket_number}/milestones : List Milestones
   *
   * @param ticketNumber (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/tickets/{ticket_number}/milestones",
    produces = { "application/json" }
  )
  public ResponseEntity<MilestoneList> getMilestonesForTicket(@PathVariable("ticket_number") Long ticketNumber, ApiPageable pageable) throws Exception {
    MilestoneList response = milestoneService.getMilestonesForTicket(ticketNumber, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /tickets/{ticket_number}/milestones/add : Add Milestone
   *
   * @param ticketNumber (required)
   * @param milestone (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/tickets/{ticket_number}/milestones/add",
    consumes = { "application/json" }
  )
  public ResponseEntity<Void> addMilestoneToTicket(@PathVariable("ticket_number") Long ticketNumber, @Valid @RequestBody Long milestone) throws Exception {
    milestoneService.addMilestoneToTicket(ticketNumber, milestone);
    return new ResponseEntity<>(HttpStatus.OK);
  }

  /**
   * POST /tickets/{ticket_number}/milestones/remove : Remove Milestone
   *
   * @param ticketNumber (required)
   * @param milestone (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/tickets/{ticket_number}/milestones/remove",
    consumes = { "application/json" }
  )
  public ResponseEntity<Void> removeMilestoneFromTicket(@PathVariable("ticket_number") Long ticketNumber, @Valid @RequestBody Long milestone) throws Exception {
    milestoneService.removeMilestoneFromTicket(ticketNumber, milestone);
    return new ResponseEntity<>(HttpStatus.OK);
  }

  /**
   * GET /projects/{project_id}/milestones : List Milestones
   *
   * @param projectId (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/projects/{project_id}/milestones",
    produces = { "application/json" }
  )
  public ResponseEntity<MilestoneList> getMilestones(@PathVariable("project_id") Long projectId, ApiPageable pageable) throws Exception {
    MilestoneList response = milestoneService.getMilestones(projectId, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /projects/{project_id}/milestones : Create a Milestone
   *
   * @param projectId (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/projects/{project_id}/milestones",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Milestone> createMilestone(@PathVariable("project_id") Long projectId, @Valid @RequestBody Milestone body) throws Exception {
    Milestone response = milestoneService.createMilestone(projectId, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /projects/{project_id}/milestones/{milestone} : Read the specified Milestone
   *
   * @param projectId (required)
   * @param milestone (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/projects/{project_id}/milestones/{milestone}",
    produces = { "application/json" }
  )
  public ResponseEntity<Milestone> getMilestone(@PathVariable("project_id") Long projectId, @PathVariable("milestone") Long milestone) throws Exception {
    Milestone response = milestoneService.getMilestone(projectId, milestone);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /projects/{project_id}/milestones/{milestone} : Replace the specified Milestone
   *
   * @param projectId (required)
   * @param milestone (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PutMapping(
    value = "/projects/{project_id}/milestones/{milestone}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Milestone> replaceMilestone(@PathVariable("project_id") Long projectId, @PathVariable("milestone") Long milestone, @Valid @RequestBody Milestone body) throws Exception {
    Milestone response = milestoneService.replaceMilestone(projectId, milestone, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /projects/{project_id}/milestones/{milestone} : Update the specified Milestone
   *
   * @param projectId (required)
   * @param milestone (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PatchMapping(
    value = "/projects/{project_id}/milestones/{milestone}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Milestone> updateMilestone(@PathVariable("project_id") Long projectId, @PathVariable("milestone") Long milestone, Milestone body) throws Exception {
    Validator.validateExRequired(body);
    Milestone response = milestoneService.updateMilestone(projectId, milestone, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /projects/{project_id}/milestones/{milestone} : Delete the specified Milestone
   *
   * @param projectId (required)
   * @param milestone (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @DeleteMapping(
    value = "/projects/{project_id}/milestones/{milestone}"
  )
  public ResponseEntity<Void> deleteMilestone(@PathVariable("project_id") Long projectId, @PathVariable("milestone") Long milestone) throws Exception {
    milestoneService.deleteMilestone(projectId, milestone);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
