/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.*;
import javax.annotation.PostConstruct;

import com.test.config.Errors;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.domain.*;
import com.test.model.*;

@Slf4j
@Service
public class ProjectService {

  @Autowired
  private ProjectRepository projectRepository;

  @PostConstruct
  private void init() {

  }

  public ObjectList getProjects(String name, ApiPageable pageable) throws ApiException {

    pageable.query.put("name", name);

    List<Project> items = projectRepository.findAll(pageable);

    Long totalCount = pageable.count ? projectRepository.count(pageable) : null;
    String nextCursor = pageable.getNextCursor(items);

    ObjectList ret = new ObjectList();
    ret.totalCount = totalCount;
    ret.nextCursor = nextCursor;
    ret.items = items;

    return ret;
  }

  public Project createProject(Project body) throws ApiException {

    Project ret = projectRepository.save(body);

    return ret;
  }

  public Project getProject(Long id) throws ApiException {

    Project ret = projectRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(Project.class, id));

    return ret;
  }

  public Project replaceProject(Long id, Project body) throws ApiException {

    Project dbEntity = projectRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(Project.class, id));

    // update dbEntity with all writeable fields
    dbEntity.replace(body);

    Project ret = projectRepository.save(dbEntity);

    return ret;
  }

  public Project updateProject(Long id, Project body) throws ApiException {

    Project dbEntity = projectRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(Project.class, id));

    // update dbEntity with all writeable fields if present
    dbEntity.update(body);

    Project ret = projectRepository.save(dbEntity);

    return ret;
  }

  public Void deleteProject(Long id) throws ApiException {

    try {
      projectRepository.deleteById(id);
    } catch (Exception e) {
      throw ApiException.entityNotFound(Project.class, id);
    }

    return null;
  }

}
