/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;
import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;

import com.test.constant.AppError;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.model.*;

@Service
public class TicketService {

  private static Logger log = LoggerFactory.getLogger(TicketService.class.getSimpleName());

  @javax.annotation.Resource
  private TicketRepository ticketRepository;

  @Autowired
  EntityManager entityManager;

  @PostConstruct
  private void init() {

  }

  public TicketList getTickets(ApiPageable pageable) throws Exception {

    List<Ticket> items = ticketRepository.findAll(pageable);

    Long totalCount = pageable.totalCount(ticketRepository.count());
    String nextCursor = pageable.nextCursor(items);

    TicketList ret = new TicketList()
        .setTotalCount(totalCount)
        .setNextCursor(nextCursor)
        .setItems(items);

    return ret;
  }

  public Ticket createTicket(Ticket body) throws Exception {

    Ticket ret = ticketRepository.save(body);

    return ret;
  }

  public Ticket getTicket(Long id) throws Exception {

    Ticket ret = ticketRepository.findById(id).orElse(null);

    if (ret == null) {
      throw new ApiException(AppError.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }

    return ret;
  }

  public Ticket replaceTicket(Long id, Ticket body) throws Exception {

    Ticket dbEntity = ticketRepository.findById(id).orElse(null);

    if (dbEntity == null) {
      throw new ApiException(AppError.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }

    // update new object with all readOnly fields from previous entry
    body.copyIdentiy(dbEntity);

    Ticket ret = ticketRepository.save(body);

    return ret;
  }

  public Ticket updateTicket(Long id, Ticket body) throws Exception {

    Ticket dbEntity = ticketRepository.findById(id).orElse(null);

    if (dbEntity == null) {
      throw new ApiException(AppError.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }

    // update dbEntity with all writeable fields if present
    Optional.ofNullable(body.getTitle()).ifPresent(v -> dbEntity.setTitle(v));
    Optional.ofNullable(body.getBody()).ifPresent(v -> dbEntity.setBody(v));
    Optional.ofNullable(body.getStatus()).ifPresent(v -> dbEntity.setStatus(v));

    Ticket ret = ticketRepository.save(dbEntity);

    return ret;
  }

  public Void deleteTicket(Long id) throws Exception {

    if (!ticketRepository.existsById(id)) {
      throw new ApiException(AppError.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }

    ticketRepository.deleteById(id);

    return null;
  }

}
