/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.service;

import com.test.domain.*;
import com.test.exception.AppException;
import com.test.model.*;
import com.test.repository.*;
import com.test.util.PredicateBuilder;

import com.querydsl.core.BooleanBuilder;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataRetrievalFailureException;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;

import java.util.*;

@Slf4j
@Service
public class TicketService {

  @Autowired
  private TicketRepository ticketRepository;

  @PostConstruct
  private void init() {

  }

  private Ticket fetchTicketFromDb(Long id) throws AppException {
    return ticketRepository.findById(id)
        .orElseThrow(() -> AppException.entityNotFound(Ticket.class, id));
  }

  public CursorPage getTickets(CursorPageable pageable, Context context) throws AppException {

    context.loadFromContext(true, false, false);
    List<String> queryParameters = Arrays.asList(); 
    BooleanBuilder predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), Ticket.class);

    CursorPage ret = ticketRepository.findAll(predicate, pageable);

    return ret;
  }

  public Ticket createTicket(Ticket body, Context context) throws AppException {

    Ticket ret = ticketRepository.save(body);

    return ret;
  }

  public Ticket getTicket(Long id, Context context) throws AppException {

    Ticket ret = fetchTicketFromDb(id);

    return ret;
  }

  public Ticket replaceTicket(Long id, Ticket body, Context context) throws AppException {

    Ticket dbEntity = fetchTicketFromDb(id);

    // update dbEntity with all writeable fields
    dbEntity.replace(body);

    Ticket ret = ticketRepository.save(dbEntity);

    return ret;
  }

  public Ticket updateTicket(Long id, Ticket body, Context context) throws AppException {

    Ticket dbEntity = fetchTicketFromDb(id);

    // update dbEntity with all writeable fields if present
    dbEntity.update(body);

    Ticket ret = ticketRepository.save(dbEntity);

    return ret;
  }

  public Void deleteTicket(Long id, Context context) throws AppException {

    try {
      ticketRepository.deleteById(id);
    }
    catch (DataRetrievalFailureException e) {
      throw AppException.entityNotFound(Ticket.class, id);
    }

    return null;
  }

}
