/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.*;
import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;

import com.test.config.Errors;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.domain.*;
import com.test.model.*;

@Service
public class UserService {

  private static Logger log = LoggerFactory.getLogger(UserService.class.getSimpleName());

  @Autowired
  private TicketRepository ticketRepository;

  @Autowired
  private UserRepository userRepository;

  @Autowired
  EntityManager entityManager;

  @PostConstruct
  private void init() {

  }

  private void validateTicketId(Long id) throws ApiException {
    if (!ticketRepository.existsById(id)) {
      throw new ApiException(Errors.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }
  }

  public ObjectList getUsersForTicket(Long ticketId, ApiPageable pageable) throws ApiException {

    // confirm existence of parent
    validateTicketId(ticketId);

    List<User> items = userRepository.findAllByTicketId(ticketId, pageable);

    Long totalCount = pageable.count ? userRepository.countByTicketId(ticketId, pageable) : null;
    String nextCursor = pageable.getNextCursor(items);

    ObjectList ret = new ObjectList();
    ret.totalCount = totalCount;
    ret.nextCursor = nextCursor;
    ret.items = items;

    return ret;
  }

  public Void addUserToTicket(Long ticketId, Long id) throws ApiException {

    // confirm existence of parent
    validateTicketId(ticketId);

    // link to parent
    Ticket ticket = entityManager.getReference(Ticket.class, ticketId);
    User user = entityManager.getReference(User.class, id);
    
    ticket.users.add(user);

    ticketRepository.save(ticket);

    return null;
  }

  public Void removeUserFromTicket(Long ticketId, Long id) throws ApiException {

    // confirm existence of parent
    validateTicketId(ticketId);

    // link to parent
    Ticket ticket = entityManager.getReference(Ticket.class, ticketId);
    User user = entityManager.getReference(User.class, id);
    
    ticket.users.remove(user);

    ticketRepository.save(ticket);

    return null;
  }

  public ObjectList getUsers(ApiPageable pageable) throws ApiException {

    List<User> items = userRepository.findAll(pageable);

    Long totalCount = pageable.count ? userRepository.count(pageable) : null;
    String nextCursor = pageable.getNextCursor(items);

    ObjectList ret = new ObjectList();
    ret.totalCount = totalCount;
    ret.nextCursor = nextCursor;
    ret.items = items;

    return ret;
  }

  public User createUser(User body) throws ApiException {

    User ret = userRepository.save(body);

    return ret;
  }

  public User getUser(Long id) throws ApiException {

    User ret = userRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(User.class, id));

    return ret;
  }

  public User replaceUser(Long id, User body) throws ApiException {

    User dbEntity = userRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(User.class, id));

    // update dbEntity with all writeable fields
    dbEntity.replace(body);

    User ret = userRepository.save(dbEntity);

    return ret;
  }

  public User updateUser(Long id, User body) throws ApiException {

    User dbEntity = userRepository.findById(id)
        .orElseThrow(() -> ApiException.entityNotFound(User.class, id));

    // update dbEntity with all writeable fields if present
    dbEntity.update(body);

    User ret = userRepository.save(dbEntity);

    return ret;
  }

  @org.springframework.transaction.annotation.Transactional
  public Void deleteUser(Long id) throws ApiException {

    try {
      userRepository.removeRelations(id);
      userRepository.deleteById(id);
    } catch (Exception e) {
      throw ApiException.entityNotFound(User.class, id);
    }

    return null;
  }

}
