/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;
import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;

import com.test.constant.AppError;
import com.test.exception.ApiException;
import com.test.repository.*;
import com.test.model.*;

@Service
public class UserService {

  private static Logger log = LoggerFactory.getLogger(UserService.class.getSimpleName());

  @javax.annotation.Resource
  private TicketRepository ticketRepository;

  @javax.annotation.Resource
  private UserRepository userRepository;

  @Autowired
  EntityManager entityManager;

  @PostConstruct
  private void init() {

  }

  private void validateTicketId(Long id) throws Exception {
    if (!ticketRepository.existsById(id)) {
      throw new ApiException(AppError.NOT_FOUND, "Ticket " + id.toString() + " does not exist");
    }
  }

  public UserList getUsersForTicket(Long ticketId, ApiPageable pageable) throws Exception {

    // confirm existence of parent
    validateTicketId(ticketId);

    List<User> items = userRepository.findByTicketId(ticketId, pageable);

    Long totalCount = pageable.totalCount(userRepository.count());
    String nextCursor = pageable.nextCursor(items);

    UserList ret = new UserList()
        .setTotalCount(totalCount)
        .setNextCursor(nextCursor)
        .setItems(items);

    return ret;
  }

  public Void addUserToTicket(Long ticketId, Long id) throws Exception {

    // confirm existence of parent
    validateTicketId(ticketId);

    // link to parent
    Ticket ticket = entityManager.getReference(Ticket.class, ticketId);
    User user = entityManager.getReference(User.class, id);
    
    ticket.addUsersItem(user);

    ticketRepository.save(ticket);

    return null;
  }

  public Void removeUserFromTicket(Long ticketId, Long id) throws Exception {

    // confirm existence of parent
    validateTicketId(ticketId);

    // link to parent
    Ticket ticket = entityManager.getReference(Ticket.class, ticketId);
    User user = entityManager.getReference(User.class, id);
    
    ticket.removeUsersItem(user);

    ticketRepository.save(ticket);

    return null;
  }

  public UserList getUsers(ApiPageable pageable) throws Exception {

    List<User> items = userRepository.findAll(pageable);

    Long totalCount = pageable.totalCount(userRepository.count());
    String nextCursor = pageable.nextCursor(items);

    UserList ret = new UserList()
        .setTotalCount(totalCount)
        .setNextCursor(nextCursor)
        .setItems(items);

    return ret;
  }

  public User createUser(User body) throws Exception {

    User ret = userRepository.save(body);

    return ret;
  }

  public User getUser(Long id) throws Exception {

    User ret = userRepository.findById(id).orElse(null);

    if (ret == null) {
      throw new ApiException(AppError.NOT_FOUND, "User " + id.toString() + " does not exist");
    }

    return ret;
  }

  public User replaceUser(Long id, User body) throws Exception {

    User dbEntity = userRepository.findById(id).orElse(null);

    if (dbEntity == null) {
      throw new ApiException(AppError.NOT_FOUND, "User " + id.toString() + " does not exist");
    }

    // update new object with all readOnly fields from previous entry
    body.copyIdentiy(dbEntity);

    User ret = userRepository.save(body);

    return ret;
  }

  public User updateUser(Long id, User body) throws Exception {

    User dbEntity = userRepository.findById(id).orElse(null);

    if (dbEntity == null) {
      throw new ApiException(AppError.NOT_FOUND, "User " + id.toString() + " does not exist");
    }

    // update dbEntity with all writeable fields if present
    Optional.ofNullable(body.getName()).ifPresent(v -> dbEntity.setName(v));

    User ret = userRepository.save(dbEntity);

    return ret;
  }

  @org.springframework.transaction.annotation.Transactional
  public Void deleteUser(Long id) throws Exception {

    if (!userRepository.existsById(id)) {
      throw new ApiException(AppError.NOT_FOUND, "User " + id.toString() + " does not exist");
    }

    userRepository.removeRelations(id);
    userRepository.deleteById(id);

    return null;
  }

}
