/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.domain.entity;

import app.server.model.AbstractPersistentObject;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

import java.util.*;

@Getter
@Setter
@Entity
@Table(name = "user")
public class UserEntity extends AbstractPersistentObject {

  @NotNull
  private String name;

  private Integer count;

  @Column(unique = true)
  private String mail;

  @JsonIgnore
  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(name = "ticket_to_user", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "ticket_id"))
  public final Set<TicketEntity> tickets = new LinkedHashSet<>();


  public void addToTickets(TicketEntity o) {
    o.getUsers().add(this);
    this.tickets.add(o);
  }

  public void removeFromTickets(TicketEntity o) {
    o.getUsers().remove(this);
    this.tickets.remove(o);
  }

}
