/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.extern.slf4j.Slf4j;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Version;

import com.test.util.IdGenerator;
import com.test.util.Json;

@Slf4j
@MappedSuperclass
public abstract class AbstractPersistentBase {

  @Id
  @GeneratedValue(generator = "optimized-sequence")
  @JsonIgnore
  private Long id;

  @JsonIgnore
  private String _uuid = IdGenerator.createId();

  @Version
  @JsonIgnore
  private Integer _version;

  public Long getId() {
    return id;
  }

  public String _uuid() {
    return _uuid;
  }

  public Integer _version() {
    return _version;
  }

  /**
   * Copies the id, uuid and version field from another Object.
   */
  public void copyIdentiy(AbstractPersistentBase o) {
    this.id = o.getId();
    this._uuid = o._uuid();
    this._version = o._version();
  }

  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || !(o instanceof AbstractPersistentBase)) {
      return false;
    }

    AbstractPersistentBase other = (AbstractPersistentBase) o;

    // if the uuid is missing, return false
    if (_uuid == null) {
      return false;
    }

    // equivalence by uuid
    return _uuid.equals(other._uuid());
  }

  public int hashCode() {
    if (_uuid != null) {
      return _uuid.hashCode();
    } else {
      return super.hashCode();
    }
  }

  public String toString() {
    String ret = new String();
    try {
      ret = Json.serializer().toString(this);
    } catch (Json.JsonException e) {
      log.error("Caught unhandeled exception:", e);
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = Json.serializer().toPrettyString(this);
    } catch (Json.JsonException e) {
      log.error("Caught unhandeled exception:", e);
    }
    return ret;
  }

}
