/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import com.test.util.*;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.extern.slf4j.Slf4j;

import javax.persistence.*;

@Slf4j
@MappedSuperclass
public abstract class AbstractPersistentBase {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @JsonIgnore
  private Long id;

  @JsonIgnore
  private String uuid = IdGenerator.createId();

  @Version
  @JsonIgnore
  private Integer uuidv;

  public Long getId() {
    return id;
  }

  public String uuid() {
    return uuid;
  }

  public Integer uuidv() {
    return uuidv;
  }

  /**
   * Copies the id, uuid and version field from another Object.
   */
  public void copyIdentiy(AbstractPersistentBase o) {
    this.id = o.getId();
    this.uuid = o.uuid();
    this.uuidv = o.uuidv();
  }

  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || !(o instanceof AbstractPersistentBase)) {
      return false;
    }

    AbstractPersistentBase other = (AbstractPersistentBase) o;

    // if the uuid is missing, return false
    if (uuid == null) {
      return false;
    }

    // equivalence by uuid
    return uuid.equals(other.uuid());
  }

  public int hashCode() {
    if (uuid != null) {
      return uuid.hashCode();
    }
    else {
      return super.hashCode();
    }
  }

  public String toString() {
    String ret = new String();
    try {
      ret = Json.serializer().toString(this);
    }
    catch (Json.JsonException e) {
      log.error("Caught unhandeled exception:", e);
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = Json.serializer().toPrettyString(this);
    }
    catch (Json.JsonException e) {
      log.error("Caught unhandeled exception:", e);
    }
    return ret;
  }

}
