/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.reflect.FieldUtils;

import javax.persistence.*;

import java.lang.reflect.Field;
import java.util.Objects;

import com.test.util.IdGenerator;

@MappedSuperclass
public abstract class AbstractPersistentObject {

  @Id
  @GeneratedValue(generator = "optimized-sequence")
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @JsonIgnore
  private String _uuid = IdGenerator.createId();

  @Version
  @JsonIgnore
  private Integer _version;


  public Long getId() {
    return id;
  }

  public String get_uuid() {
    return _uuid;
  }

  public Integer get_version() {
    return _version;
  }


  /**
   * Copies the id, uuid and version field from another Object.
   */
  public void copyIdentiy(AbstractPersistentObject o) {
    this.id = o.getId();
    this._uuid = o.get_uuid();
    this._version = o.get_version();
  }

  /**
   * Updates all writeable fields.
   */
  public <T extends AbstractPersistentObject> void replace(T o) {
    reflect(o, false);
  }

  /**
   * Updates all writeable fields and ignores null values.
   */
  public <T extends AbstractPersistentObject> void update(T o) {
    reflect(o, true);
  }

  /**
   * Copy all relevant fields of one object to another utilizing reflection.
   * 
   * Ignores fields annotated with @JsonIgnore
   * Ignores fields annotated with @JsonProperty(access = JsonProperty.Access.READ_ONLY)
   */
  private <T extends AbstractPersistentObject> void reflect(T o, boolean skipNull) {

    Field[] fields = o.getClass().getDeclaredFields();

    // copy fields if:
    // not annotated with JsonIgnore
    // not annotated with JsonProperty or JsonProperty.Access != READ_ONLY
    for (Field field : fields) {
      if (!field.isAnnotationPresent(JsonIgnore.class) &&
          (!field.isAnnotationPresent(JsonProperty.class) ||
              field.getAnnotation(JsonProperty.class).access() != JsonProperty.Access.READ_ONLY)) {

        try {
          if (!skipNull || skipNull && Objects.nonNull(field.get(o))) {
            FieldUtils.writeField(this, field.getName(), field.get(o), true);
          }
        } catch (IllegalAccessException | IllegalArgumentException e) {
        }
      }
    }
  }

  /**
   * Removes all relations from a give Object.
   * 
   * Affects fields annotated with OneToOne, OneToMany, ManyToOne, ManyToMany
   */
  public void removeRelations() {

    Field[] fields = this.getClass().getDeclaredFields();

    // null fields if:
    // annotated with OneToOne, OneToMany, ManyToOne, ManyToMany
    for (Field field : fields) {
      if (field.isAnnotationPresent(OneToOne.class) || field.isAnnotationPresent(OneToMany.class)
          || field.isAnnotationPresent(ManyToOne.class) || field.isAnnotationPresent(ManyToMany.class)) {

        try {
          FieldUtils.writeField(this, field.getName(), null, true);
        } catch (IllegalAccessException | IllegalArgumentException e) {
        }
      }
    }
  }

  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || !(o instanceof AbstractPersistentObject)) {
      return false;
    }

    AbstractPersistentObject other = (AbstractPersistentObject) o;

    // if the uuid is missing, return false
    if (_uuid == null) {
      return false;
    }

    // equivalence by uuid
    return _uuid.equals(other.get_uuid());
  }

  public int hashCode() {
    if (_uuid != null) {
      return _uuid.hashCode();
    } else {
      return super.hashCode();
    }
  }

  public String toString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toPrettyString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

}
