/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.time.OffsetDateTime;
import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;
import org.springframework.format.annotation.DateTimeFormat;

@MappedSuperclass
public class BaseType {

  @Id
  @GeneratedValue(generator="optimized-sequence")
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @NotNull
  @JsonProperty(value = "name", required = true)
  private String name;

  @JsonProperty(value = "description")
  private String description;

  @JsonProperty(value = "creation_by", access = JsonProperty.Access.READ_ONLY)
  private String creationBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "creation_date", access = JsonProperty.Access.READ_ONLY)
  private OffsetDateTime creationDate;

  @JsonProperty(value = "last_update_by", access = JsonProperty.Access.READ_ONLY)
  private String lastUpdateBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "last_update_date", access = JsonProperty.Access.READ_ONLY)
  private OffsetDateTime lastUpdateDate;

  @Column(columnDefinition = "BINARY(1048576)")
  @org.hibernate.annotations.Type(type = "serializable")
  @JsonProperty(value = "meta_inf")
  private Object metaInf;



  /**
   * id
   */
  public Long getId() {
    return id;
  }

  public BaseType setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * name
   */
  public String getName() {
    return name;
  }

  public BaseType setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * description
   */
  public String getDescription() {
    return description;
  }

  public BaseType setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * creationBy
   */
  public String getCreationBy() {
    return creationBy;
  }

  public BaseType setCreationBy(String creationBy) {
    this.creationBy = creationBy;
    return this;
  }

  /**
   * creationDate
   */
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public BaseType setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * lastUpdateBy
   */
  public String getLastUpdateBy() {
    return lastUpdateBy;
  }

  public BaseType setLastUpdateBy(String lastUpdateBy) {
    this.lastUpdateBy = lastUpdateBy;
    return this;
  }

  /**
   * lastUpdateDate
   */
  public OffsetDateTime getLastUpdateDate() {
    return lastUpdateDate;
  }

  public BaseType setLastUpdateDate(OffsetDateTime lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
    return this;
  }

  /**
   * metaInf
   */
  public Object getMetaInf() {
    return metaInf;
  }

  public BaseType setMetaInf(Object metaInf) {
    this.metaInf = metaInf;
    return this;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseType basetype = (BaseType) o;
    return Objects.equals(this.id, basetype.id) &&
        Objects.equals(this.name, basetype.name) &&
        Objects.equals(this.description, basetype.description) &&
        Objects.equals(this.creationBy, basetype.creationBy) &&
        Objects.equals(this.creationDate, basetype.creationDate) &&
        Objects.equals(this.lastUpdateBy, basetype.lastUpdateBy) &&
        Objects.equals(this.lastUpdateDate, basetype.lastUpdateDate) &&
        Objects.equals(this.metaInf, basetype.metaInf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, creationBy, creationDate, lastUpdateBy, lastUpdateDate, metaInf);
  }

  @Override
  public String toString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toPrettyString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public static BaseType fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, BaseType.class);
  }

}
