/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

public interface PersistentObject {

    public String getUUID();

    public PersistentObject setUUID(String id);

    public Integer getVersion();

    public PersistentObject setVersion(Integer version);
}

