/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.time.OffsetDateTime;
import java.util.*;
import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;
import org.springframework.format.annotation.DateTimeFormat;

@Entity
public class Project extends AbstractPersistentObject {

  @NotNull
  @JsonProperty(value = "name", required = true)
  public String name;

  @JsonProperty(value = "description")
  public String description;

  @JsonProperty(value = "creation_by", access = JsonProperty.Access.READ_ONLY)
  public String creationBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "creation_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime creationDate;

  @JsonProperty(value = "last_update_by", access = JsonProperty.Access.READ_ONLY)
  public String lastUpdateBy;

  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
  @JsonProperty(value = "last_update_date", access = JsonProperty.Access.READ_ONLY)
  public OffsetDateTime lastUpdateDate;

  @Column(columnDefinition = "BINARY(1048576)")
  @org.hibernate.annotations.Type(type = "serializable")
  @JsonProperty(value = "meta_inf")
  public Object metaInf;

  @JsonProperty(value = "archive", access = JsonProperty.Access.WRITE_ONLY)
  public Boolean archive;

  @OneToMany(mappedBy = "project", fetch = FetchType.LAZY, orphanRemoval = true)
  @JsonIgnore
  private Set<Role> roles = new LinkedHashSet<>();



  /**
   * roles
   */
  public Set<Role> getRoles() {
    return roles;
  }

  public Project setRoles(Set<Role> roles) {
    this.roles = roles;
    return this;
  }

  public Project addRolesItem(Role rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

  public Project removeRolesItem(Role rolesItem) {
    this.roles.remove(rolesItem);
    return this;
  }



  public static Project fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, Project.class);
  }

}
