/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.util.*;
import javax.persistence.*;
import javax.validation.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;


public class ProjectList {

  @NotNull
  @Valid
  @JsonProperty(value = "items", required = true)
  private List<Project> items = new ArrayList<>();

  @JsonProperty(value = "next_cursor")
  private String nextCursor;

  @JsonProperty(value = "total_count")
  private Long totalCount;

  /**
   * items
   */
  public List<Project> getItems() {
    return items;
  }

  public ProjectList setItems(List<Project> items) {
    this.items = items;
    return this;
  }

  public ProjectList addItemsItem(Project itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

  public ProjectList removeItemsItem(Project itemsItem) {
    this.items.remove(itemsItem);
    return this;
  }

  /**
   * nextCursor
   */
  public String getNextCursor() {
    return nextCursor;
  }

  public ProjectList setNextCursor(String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * totalCount
   */
  public Long getTotalCount() {
    return totalCount;
  }

  public ProjectList setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectList projectlist = (ProjectList) o;
    return Objects.equals(this.items, projectlist.items) &&
        Objects.equals(this.nextCursor, projectlist.nextCursor) &&
        Objects.equals(this.totalCount, projectlist.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, nextCursor, totalCount);
  }

  @Override
  public String toString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toPrettyString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public static ProjectList fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, ProjectList.class);
  }

}
