/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Role {

  @NotNull
  @JsonProperty(value = "role", required = true)
  private Long role;

  @Valid
  @JsonProperty(value = "users")
  private List<User> users;

  /**
   * role
   */
  public Long getRole() {
    return role;
  }

  public Role setRole(Long role) {
    this.role = role;
    return this;
  }

  /**
   * users
   */
  public List<User> getUsers() {
    return users;
  }

  public Role setUsers(List<User> users) {
    this.users = users;
    return this;
  }

  public Role addUsersItem(User usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<>();
    }
    this.users.add(usersItem);
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Role role = (Role) o;
    return Objects.equals(this.role, role.role) &&
        Objects.equals(this.users, role.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, users);
  }

  @Override
  public String toString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toPrettyString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public static Role fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, Role.class);
  }

}
