/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.util.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.*;

@Entity
public class Role extends AbstractPersistentObject {

  @Id
  @GeneratedValue(generator="optimized-sequence")
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @NotNull
  @JsonProperty(value = "name", required = true)
  private String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name="project_id")
  @JsonIgnore
  private Project project;



  /**
   * id
   */
  public Long getId() {
    return id;
  }

  public Role setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * name
   */
  public String getName() {
    return name;
  }

  public Role setName(String name) {
    this.name = name;
    return this;
  }

  /**
   * project
   */
  public Project getProject() {
    return project;
  }

  public Role setProject(Project project) {
    this.project = project;
    return this;
  }



  public static Role fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, Role.class);
  }

}
