/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import javax.persistence.*;
import com.fasterxml.jackson.annotation.*;

public enum Status {

  OPEN("OPEN"),
  TO_DO("TO_DO"),
  CLOSED("CLOSED");

  private String value;

  Status(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Status fromValue(String value) {
    for (Status b : Status.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

}
