/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.Valid;
import javax.validation.constraints.*;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UserList {

  @NotNull
  @Valid
  @JsonProperty(value = "items", required = true)
  private List<User> items;

  @JsonProperty(value = "next_cursor")
  private String nextCursor;

  @JsonProperty(value = "total_count")
  private Long totalCount;

  /**
   * items
   */
  public List<User> getItems() {
    return items;
  }

  public UserList setItems(List<User> items) {
    this.items = items;
    return this;
  }

  public UserList addItemsItem(User itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * nextCursor
   */
  public String getNextCursor() {
    return nextCursor;
  }

  public UserList setNextCursor(String nextCursor) {
    this.nextCursor = nextCursor;
    return this;
  }

  /**
   * totalCount
   */
  public Long getTotalCount() {
    return totalCount;
  }

  public UserList setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserList userlist = (UserList) o;
    return Objects.equals(this.items, userlist.items) &&
        Objects.equals(this.nextCursor, userlist.nextCursor) &&
        Objects.equals(this.totalCount, userlist.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, nextCursor, totalCount);
  }

  @Override
  public String toString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public String toPrettyString() {
    String ret = new String();
    try {
      ret = com.test.util.Json.serializer().toPrettyString(this);
    } catch (com.test.util.Json.JsonException e) {
      e.printStackTrace();
    }
    return ret;
  }

  public static UserList fromJson(String json)
      throws com.test.util.Json.JsonException {
    return com.test.util.Json.serializer().fromJson(json, UserList.class);
  }

}
