/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.incident.service;

import app.server.common.constants.*;
import app.server.common.db.*;
import app.server.common.exception.AppException;
import app.server.common.exception.AppExceptionUtil;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.PredicateBuilder;
import app.server.incident.db.*;
import app.server.incident.dto.*;
import app.server.incident.mapper.*;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@AllArgsConstructor
public class TicketService {

    final TicketRepository ticketRepository;

    final TicketMapper ticketMapper;

    TicketEntity fetchTicketFromDb(String id) throws AppException {
        return ticketRepository.findByUid(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(Ticket.class, id));
    }

    @Transactional(readOnly = true)
    public CursorPage<Ticket> getTickets(CursorPageable pageable) throws AppException {

        var predicate = PredicateBuilder.build(TicketEntity.class);

        var cursorPage = ticketRepository.findAll(predicate, pageable);

        var ticketEntities = cursorPage.items();
        var ticketDtos = ticketEntities.stream().map(ticketMapper::toResponse).toList();

        return new CursorPage<>(ticketDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public Ticket createTicket(TicketRequest body) throws AppException {

        var ticketEntity = ticketMapper.toEntity(body);

        ticketEntity = ticketRepository.save(ticketEntity);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional(readOnly = true)
    public Ticket getTicket(String id) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional
    public Ticket updateTicket(String id, TicketRequest body) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        // update dbEntity with all writeable fields - nulls included
        ticketMapper.update(body, ticketEntity);

        ticketEntity = ticketRepository.save(ticketEntity);

        return ticketMapper.toResponse(ticketEntity);
    }

    @Transactional
    public Void deleteTicket(String id) throws AppException {

        var ticketEntity = fetchTicketFromDb(id);

        ticketRepository.delete(ticketEntity);

        return null;
    }
}
