/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.config;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.Charset;
import javax.servlet.http.HttpServletRequest;
import com.fasterxml.jackson.dataformat.yaml.YAMLMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Controller;
import org.springframework.util.StreamUtils;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Home redirection to OpenAPI api documentation
 */
@Controller
public class HomeController {

  private static YAMLMapper yamlMapper = new YAMLMapper();

  @Value("classpath:/openapi.yaml")
  private Resource openapi;

  @Bean
  public String openapiContent() throws IOException {
    try (InputStream is = openapi.getInputStream()) {
      return StreamUtils.copyToString(is, Charset.defaultCharset());
    }
  }

  @GetMapping(value = "/api/openapi.yaml", produces = "application/vnd.oai.openapi")
  @ResponseBody
  public String openapiYaml() throws IOException {
    return openapiContent();
  }

  @GetMapping(value = "/api/openapi.json", produces = "application/json")
  @ResponseBody
  public Object openapiJson() throws IOException {
    return yamlMapper.readValue(openapiContent(), Object.class);
  }

  @RequestMapping("/api")
  public String index() {
    return "redirect:/api/swagger-ui/index.html?url=../openapi.json";
  }

  @RequestMapping(value = {"/", "/{x:[\\w\\-]+}", "/{x:^(?!api$).*$}/**/{y:[\\w\\-]+}"})
  public String getIndex(HttpServletRequest request) {
    // This is very important so our routing is handled by the frontend
    // '/' - matches root
    // '/{x:[\\w\\-]+}' - matches everything up to the second /.
    // '/{x:^(?!api$).*$}/**/{y:[\\w\\-]+}' - matches everything that doesn't start with api.
    return "/index.html";
  }

}
