/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.*;
import java.util.stream.Collectors;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.jeasy.random.EasyRandom;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;

import com.test.domain.*;
import com.test.model.ApiPageable;
import com.test.util.Json;

@DataJpaTest
@Import(com.test.TestConfig.class)
public class ProjectRepositoryTest {

  @Autowired
  private EasyRandom easyRandom;

  @Autowired
  private ProjectRepository projectRepository;

  @Test
  public void whenSave_thenFind() {

    // Given
    Project testData = easyRandom.nextObject(Project.class);
    testData.removeRelations();

    // When
    Project dbData = projectRepository.saveAndFlush(testData);
    Project findData = projectRepository.findById(dbData.getId()).orElse(null);
    testData.copyIdentiy(findData);

    // Then
    ObjectNode node1 = Json.serializer().nodeFromObject(testData);
    ObjectNode node2 = Json.serializer().nodeFromObject(findData);
    assertEquals(node1, node2);
  }

  @Test
  public void whenDelete_thenCountZero() {

    // Given
    Project testData = easyRandom.nextObject(Project.class);
    testData.removeRelations();
    Project dbData = projectRepository.saveAndFlush(testData);

    // When
    projectRepository.delete(dbData);

    // Then
    long count = projectRepository.count();
    assertEquals(0, count);
  }

  @Test
  public void whenCount_thenUseQuerie() {

    // Given
    List<Project> testData = easyRandom.objects(Project.class, 5).collect(Collectors.toList());
    testData.forEach(x -> x.removeRelations());
    List<Project> dbData = projectRepository.saveAllAndFlush(testData);

    ApiPageable pageable = new ApiPageable(null, null, null);
    pageable.query.put("name", dbData.get(0).name);

    // When
    long count = projectRepository.count(pageable);

    // Then
    assertEquals(1, count);
  }

  @Test
  public void whenFindAll_thenPaginate() {

    // Given
    List<Project> testData = easyRandom.objects(Project.class, 5).collect(Collectors.toList());
    testData.forEach(x -> x.removeRelations());
    projectRepository.saveAllAndFlush(testData);

    // When
    String cursor = null;
    int idx = 0;

    do {
      ApiPageable pageable = new ApiPageable(cursor, 1l, null);
      List<Project> findData = projectRepository.findAll(pageable);

      cursor = pageable.getNextCursor(findData);

      assertEquals(1, findData.size());

      idx++;
    } while (cursor != null);

    // Then
    assertEquals(5, idx);
  }

}
