from pathlib import Path

import pytest

from tests.e2e import assert_schema
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2ERequireAndUnique(BaseE2ETest):
    """Test E2E for REQUIRE_AND_UNIQUE testcase"""

    TESTCASE = """\
      type TableFour {
        aaa: String!
        bbb: [String]!
        ccc: String @unique
        ddd: [String] @unique
        eee: String! @unique
        fff: [String]! @unique
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema is correct"""
        expected_schema = """\
          create table if not exists T_TABLE_FOUR (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            aaa TEXT not null,
            bbb TEXT [] not null,
            ccc TEXT unique,
            ddd TEXT [] unique,
            eee TEXT not null unique,
            fff TEXT [] not null unique
          );
        """

        assert_schema(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        pass

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""

        pass

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""

        pass
