/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.repository;

import app.server.domain.entity.RoleEntity;

import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface RoleRepository extends AbstractRepository<RoleEntity, Long> {

  public Optional<RoleEntity> findByProjectIdAndId(Long projectId, Long id);

  public Optional<RoleEntity> findByProjectIdAndUid(Long projectId, String uid);
}
