/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.project.db;

import app.server.common.db.AbstractRepository;
import app.server.common.db.BaseRepository;
import app.server.project.db.ProjectEntity;
import java.util.Optional;
import org.springframework.stereotype.Repository;

@Repository
public interface ProjectRepository extends AbstractRepository<ProjectEntity, Long> {
}
