from pathlib import Path

import pytest

from tests.e2e import assert_mvn, assert_postgres
from tests.e2e.base_e2e_test import BaseE2ETest


class TestE2ECustomScalars(BaseE2ETest):
    """Test E2E for custom scalar handling across all generators"""

    TESTCASE = """\
      scalar Email @openapi("string, format: email") @spring("String") @postgres("TEXT")

      scalar Decimal @openapi("string, pattern: ^(-)?[0-9][0-9]*(?:.[0-9]{1,18})?$") @spring("String, entity: java.math.BigDecimal, pattern: ^(-)?[0-9][0-9]*(?:.[0-9]{1,18})?$") @postgres("TEXT")

      scalar WalletAddress @openapi("string, pattern: ^(0x)?[0-9a-zA-Z]+$") @spring("String, pattern: ^(0x)?[0-9a-zA-Z]+$") @postgres("TEXT")

      scalar BigInt @openapi("string, pattern: ^-?[0-9]{1,38}$") @spring("String, entity: java.math.BigInteger, pattern: ^-?[0-9]{1,38}$") @postgres("TEXT")

      type User {
        email: Email!
        walletAddress: WalletAddress
        balance: Decimal
        tokenCount: BigInt
      }
    """

    def test_postgres(self, postgres_schema: str) -> None:
        """asserts generated Postgres schema uses @postgres directive mappings"""
        expected_schema = """\
          create table if not exists T_USER (
            id BIGINT generated by default as identity primary key,
            uid VARCHAR unique,
            iv INTEGER,
            email TEXT not null,
            wallet_address TEXT,
            balance TEXT,
            token_count TEXT
          );
        """

        assert_postgres(postgres_schema, expected_schema)

    def test_openapi(self, openapi_schema: dict) -> None:
        """asserts generated OpenAPI spec is correct"""

        schemas = openapi_schema["components"]["schemas"]

        user = schemas["User"]
        user_props = user["properties"]

        assert user_props["email"]["type"] == "string"
        assert user_props["email"]["format"] == "email"
        assert "id" in user["required"]
        assert "email" in user["required"]

        assert user_props["walletAddress"]["type"] == "string"
        assert user_props["walletAddress"]["pattern"] == "^(0x)?[0-9a-zA-Z]+$"
        assert "format" not in user_props["walletAddress"]

        assert user_props["balance"]["type"] == "string"
        assert user_props["balance"]["pattern"] == "^(-)?[0-9][0-9]*(?:.[0-9]{1,18})?$"
        assert "format" not in user_props["balance"]

        assert user_props["tokenCount"]["type"] == "string"
        assert user_props["tokenCount"]["pattern"] == "^-?[0-9]{1,38}$"
        assert "format" not in user_props["tokenCount"]

    def test_spring(self, srcgen: Path) -> None:
        """asserts generated Spring Boot code is correct"""
        src_root = srcgen / "src" / "main" / "java"
        assert src_root.exists()

        user_entity_files = list(src_root.rglob("UserEntity.java"))
        assert len(user_entity_files) == 1

        entity_content = user_entity_files[0].read_text(encoding="utf-8")

        assert "private String email;" in entity_content
        assert "private String walletAddress;" in entity_content
        assert "private java.math.BigDecimal balance;" in entity_content
        assert "private java.math.BigInteger tokenCount;" in entity_content

        user_request_files = list(src_root.rglob("UserRequest.java"))
        assert len(user_request_files) == 1

        request_content = user_request_files[0].read_text(encoding="utf-8")

        assert "String email" in request_content
        assert "@NotNull" in request_content

        assert "String walletAddress" in request_content
        assert '@Pattern(regexp = "^(0x)?[0-9a-zA-Z]+$")' in request_content

        assert "String balance" in request_content
        assert '@Pattern(regexp = "^(-)?[0-9][0-9]*(?:.[0-9]{1,18})?$")' in request_content

        assert "String tokenCount" in request_content
        assert '@Pattern(regexp = "^-?[0-9]{1,38}$")' in request_content

    @pytest.mark.integration
    def test_integration(self, srcgen: Path) -> None:
        """runs mvn clean test to verify generated code compiles and tests pass"""
        assert_mvn()
