/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "app")
public class AppProperties {

  public final String name;

  public AppProperties(String name) {
    this.name = name;

  }

}
