/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.dto;

import app.server.common.model.AbstractClass;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import lombok.extern.jackson.Jacksonized;

import jakarta.validation.constraints.*;

@Getter
@Setter
@Builder
@Jacksonized
@EqualsAndHashCode(callSuper = false)
public class Role extends AbstractClass {

  @Min(0)
  @Max(Long.MAX_VALUE)
  @JsonProperty(value = "id", required = true, access = JsonProperty.Access.READ_ONLY)
  private Long id;

  @NonNull
  @NotNull
  @Size(min = 0, max = 255)
  @JsonProperty(value = "name", required = true)
  private String name;

}
