/**
 * NOTE: This class was generated by QSDL.
 */
package com.test.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.test.model.*;
import com.test.service.*;
import com.test.util.Validator;


@Validated
@RequestMapping("${server.base-path:/}")
@Controller
public class TicketController {

  private final NativeWebRequest request;

  @Autowired
  TicketService TicketService;

  @Autowired
  public TicketController(NativeWebRequest request) {
    this.request = request;
  }

  public Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /projects/{project_id}/tickets : List Tickets
   *
   * @param projectId (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/projects/{project_id}/tickets",
    produces = { "application/json" }
  )
  public ResponseEntity<TicketList> getTickets(@PathVariable("project_id") Long projectId, ApiPageable pageable) throws Exception {
    TicketList response = TicketService.getTickets(projectId, pageable);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * POST /projects/{project_id}/tickets : Create a Ticket
   *
   * @param projectId (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PostMapping(
    value = "/projects/{project_id}/tickets",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> createTicket(@PathVariable("project_id") Long projectId, @Valid @RequestBody Ticket body) throws Exception {
    Ticket response = TicketService.createTicket(projectId, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * GET /projects/{project_id}/tickets/{number} : Read the specified Ticket
   *
   * @param projectId (required)
   * @param number (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @GetMapping(
    value = "/projects/{project_id}/tickets/{number}",
    produces = { "application/json" }
  )
  public ResponseEntity<Ticket> getTicket(@PathVariable("project_id") Long projectId, @PathVariable("number") Long number) throws Exception {
    Ticket response = TicketService.getTicket(projectId, number);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PUT /projects/{project_id}/tickets/{number} : Replace the specified Ticket
   *
   * @param projectId (required)
   * @param number (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PutMapping(
    value = "/projects/{project_id}/tickets/{number}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> replaceTicket(@PathVariable("project_id") Long projectId, @PathVariable("number") Long number, @Valid @RequestBody Ticket body) throws Exception {
    Ticket response = TicketService.replaceTicket(projectId, number, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * PATCH /projects/{project_id}/tickets/{number} : Update the specified Ticket
   *
   * @param projectId (required)
   * @param number (required)
   * @param body
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @PatchMapping(
    value = "/projects/{project_id}/tickets/{number}",
    produces = { "application/json" },
    consumes = { "application/json" }
  )
  public ResponseEntity<Ticket> updateTicket(@PathVariable("project_id") Long projectId, @PathVariable("number") Long number, @RequestBody Ticket body) throws Exception {
    Validator.validateExRequired(body);
    Ticket response = TicketService.updateTicket(projectId, number, body);
    return new ResponseEntity<>(response, HttpStatus.OK);
  }

  /**
   * DELETE /projects/{project_id}/tickets/{number} : Delete the specified Ticket
   *
   * @param projectId (required)
   * @param number (required)
   * @return OK (status code 200)
   *         or Unexpected error (status code default)
   */
  @DeleteMapping(
    value = "/projects/{project_id}/tickets/{number}"
  )
  public ResponseEntity<Void> deleteTicket(@PathVariable("project_id") Long projectId, @PathVariable("number") Long number) throws Exception {
    TicketService.deleteTicket(projectId, number);
    return new ResponseEntity<>(HttpStatus.OK);
  }

}
