/**
 * NOTE: This class was generated by QSDL.
 */
package app.server.user.service;

import app.server.common.constants.*;
import app.server.common.db.*;
import app.server.common.dto.*;
import app.server.common.exception.AppException;
import app.server.common.exception.AppExceptionUtil;
import app.server.common.mapper.*;
import app.server.common.model.Context;
import app.server.common.model.CursorPage;
import app.server.common.model.CursorPageable;
import app.server.common.util.PredicateBuilder;
import app.server.user.db.*;
import app.server.user.dto.*;
import app.server.user.mapper.*;
import java.util.Arrays;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@AllArgsConstructor
public class UserService {

    final TicketRepository ticketRepository;

    final UserRepository userRepository;

    final UserMapper userMapper;

    UserEntity fetchUserFromDb(String id) throws AppException {
        return userRepository.findByUid(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(UserResponse.class, id));
    }

    UserEntity fetchUserFromTicketFromDb(Long ticketId, String id) throws AppException {
        return userRepository.findByTicketsIdAndUid(ticketId, id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(UserResponse.class, id));
    }

    TicketEntity fetchTicketFromDb(String id) throws AppException {
        return ticketRepository.findByUid(id)
                .orElseThrow(() -> AppExceptionUtil.entityNotFound(TicketResponse.class, id));
    }

    public CursorPage<UserResponse> getUsersForTicket(String ticketId, CursorPageable pageable, Context context) throws AppException {

        // confirm existence of parent
        // should be optimized with something like getReferenceById
        var ticketEntity = fetchTicketFromDb(ticketId);

        var queryParameters = Arrays.<String>asList();
        var predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), UserEntity.class);
        predicate.and(QUserEntity.userEntity.tickets.any().id.eq(ticketEntity.getId()));

        var cursorPage = userRepository.findAll(predicate, pageable);

        var userEntities = cursorPage.items();
        var userDtos = userEntities.stream().map(userMapper::toResponse).toList();

        return new CursorPage<>(userDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public Void addUserToTicket(String ticketId, String id, Context context) throws AppException {

        // get and confirm existence
        var ticketEntity = fetchTicketFromDb(ticketId);

        var userEntity = fetchUserFromDb(id);

        if (userEntity.tickets.contains(ticketEntity)) {
            throw AppExceptionUtil.entityAlreadyAdded(UserResponse.class, id);
        }

        userEntity.addToTickets(ticketEntity);

        userRepository.save(userEntity);

        return null;
    }

    @Transactional
    public Void removeUserFromTicket(String ticketId, String id, Context context) throws AppException {

        // get and confirm existence
        var ticketEntity = fetchTicketFromDb(ticketId);

        var userEntity = fetchUserFromTicketFromDb(ticketEntity.getId(), id);

        userEntity.removeFromTickets(ticketEntity);

        userRepository.save(userEntity);

        return null;
    }

    public CursorPage<UserResponse> getUsers(CursorPageable pageable, Context context) throws AppException {

        var queryParameters = Arrays.<String>asList();
        var predicate = PredicateBuilder.build(context.getParameterMap(queryParameters), UserEntity.class);

        var cursorPage = userRepository.findAll(predicate, pageable);

        var userEntities = cursorPage.items();
        var userDtos = userEntities.stream().map(userMapper::toResponse).toList();

        return new CursorPage<>(userDtos, cursorPage.nextCursor(), cursorPage.totalCount());
    }

    @Transactional
    public UserResponse createUser(UserRequest body, Context context) throws AppException {

        var userEntity = userMapper.toEntity(body);

        userEntity = userRepository.save(userEntity);

        return userMapper.toResponse(userEntity);
    }

    public UserResponse getUser(String id, Context context) throws AppException {

        var userEntity = fetchUserFromDb(id);

        return userMapper.toResponse(userEntity);
    }

    @Transactional
    public UserResponse updateUser(String id, UserRequest body, Context context) throws AppException {

        var userEntity = fetchUserFromDb(id);

        // update dbEntity with all writeable fields - nulls included
        userMapper.update(body, userEntity);

        userEntity = userRepository.save(userEntity);

        return userMapper.toResponse(userEntity);
    }

    @Transactional
    public Void deleteUser(String id, Context context) throws AppException {

        var userEntity = fetchUserFromDb(id);

        userRepository.delete(userEntity);

        return null;
    }
}
